[package]
name = "draw-i16"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ranged_integers = { git = "https://github.com/disiamylborane/ranged_integers" }

