//! A module with the standard glyph table

#![allow(missing_docs)]
#![allow(clippy::empty_line_after_doc_comments)]

use super::font::*;
use ranged_integers::*;
use GlyphConnectionType::*;

/// The standard glyph tables captured by [crate::DrawableMethods::text]

// 2024 steps, 415 glyphs, ~6902 bytes

pub const TABLES: [GlyphTable; 4] = [
    GLYPHS_LATIN,
    GLYPHS_LATIN_EXTRA,
    GLYPHS_GREEK,
    GLYPHS_CYRILLIC,
];

macro_rules! two_steps {
    ($x1:literal, $y1:literal, $z1:expr; $x2:literal, $y2:literal, $z2:expr) => {
        GlyphStep::to_gdata(
            GlyphStep{coord: GlyphCoord{x: r!([] $x1), y: r!([] $y1)}, tp: $z1},
            GlyphStep{coord: GlyphCoord{x: r!([] $x2), y: r!([] $y2)}, tp: $z2},
        )
    };
}

pub const GLYPHS_LATIN : GlyphTable = GlyphTable {
    basechar: ' ',
    addr: &[0, 1, 5, 9, 17, 21, 37, 45, 47, 50, 53, 59, 63, 66, 68, 70, 72, 77, 80, 87, 95, 99, 103, 110, 113, 122, 129, 133, 137, 140, 144, 147, 156, 170, 175, 180, 185, 188, 193, 197, 203, 208, 214, 218, 222, 224, 228, 231, 236, 239, 243, 247, 254, 257, 261, 263, 267, 270, 273, 276, 280, 282, 286, 289, 291, 293, 301, 304, 307, 311, 317, 322, 328, 332, 336, 342, 346, 349, 356, 361, 366, 370, 374, 378, 387, 392, 396, 399, 404, 408, 415, 419, 428, 430, 439],
    data: &[
        two_steps!(0, 0, Break; 6, 1, Break),
        two_steps!(6, 15, Outline { thick: true, update: true }; 6, 23, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 4, 1, Break),
        two_steps!(4, 7, Outline { thick: true, update: true }; 8, 1, Break),
        two_steps!(8, 7, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 24, Outline { thick: true, update: true }; 0, 6, Break),
        two_steps!(12, 6, Outline { thick: false, update: true }; 0, 18, Break),
        two_steps!(12, 18, Outline { thick: false, update: true }; 3, 5, Control),
        two_steps!(0, 0, Break; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: false, update: false }; 6, 4, Break),
        two_steps!(5, 2, Control; 3, 1, Outline { thick: false, update: true }),
        two_steps!(1, 2, Control; 0, 4, Outline { thick: false, update: true }),
        two_steps!(1, 6, Control; 4, 7, Outline { thick: false, update: true }),
        two_steps!(12, 1, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(7, 17, Outline { thick: false, update: true }; 11, 18, Control),
        two_steps!(12, 21, Outline { thick: false, update: true }; 11, 23, Control),
        two_steps!(9, 24, Outline { thick: false, update: true }; 7, 23, Control),
        two_steps!(6, 21, Outline { thick: false, update: true }; 12, 24, Break),
        two_steps!(6, 11, Outline { thick: false, update: true }; 3, 3, Control),
        two_steps!(12, 2, Outline { thick: false, update: false }; 0, 18, Control),
        two_steps!(3, 24, Outline { thick: true, update: true }; 8, 22, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 6, Outline { thick: true, update: true }; 7, 1, Break),
        two_steps!(4, 12, Control; 7, 24, Outline { thick: true, update: true }),
        two_steps!(5, 1, Break; 8, 12, Control),
        two_steps!(5, 24, Outline { thick: true, update: true }; 6, 12, Break),
        two_steps!(6, 5, Outline { thick: false, update: false }; 1, 9, Outline { thick: false, update: false }),
        two_steps!(11, 9, Outline { thick: false, update: false }; 2, 17, Outline { thick: true, update: false }),
        two_steps!(10, 17, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(12, 12, Outline { thick: true, update: true }; 6, 5, Break),
        two_steps!(6, 19, Outline { thick: false, update: true }; 8, 21, Break),
        two_steps!(8, 24, Outline { thick: true, update: true }; 6, 28, Outline { thick: false, update: true }),
        two_steps!(3, 12, Break; 9, 12, Outline { thick: false, update: true }),
        two_steps!(6, 23, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(11, 2, Break; 1, 23, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 0, 12, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 12, Oval { right: true }),
        two_steps!(6, 1, Oval { right: true }; 2, 12, Break),
        two_steps!(9, 1, Outline { thick: false, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 2, 3, Control),
        two_steps!(7, 2, Outline { thick: false, update: true }; 12, 6, Control),
        two_steps!(7, 14, Outline { thick: false, update: true }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 8, 2, Control),
        two_steps!(12, 6, Outline { thick: false, update: true }; 9, 10, Control),
        two_steps!(4, 12, Outline { thick: false, update: true }; 9, 14, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 7, 23, Control),
        two_steps!(0, 23, Outline { thick: true, update: true }; 9, 24, Break),
        two_steps!(9, 1, Outline { thick: true, update: true }; 0, 17, Outline { thick: false, update: true }),
        two_steps!(12, 17, Outline { thick: true, update: true }; 12, 2, Outline { thick: false, update: false }),
        two_steps!(0, 11, Outline { thick: true, update: true }; 12, 17, Oval { right: false }),
        two_steps!(0, 24, Oval { right: false }; 12, 2, Break),
        two_steps!(2, 5, Control; 0, 18, Outline { thick: true, update: true }),
        two_steps!(6, 25, Oval { right: true }; 12, 19, Oval { right: true }),
        two_steps!(6, 13, Oval { right: true }; 1, 13, Outline { thick: true, update: false }),
        two_steps!(12, 2, Outline { thick: false, update: true }; 7, 12, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 12, Break),
        two_steps!(12, 6, Oval { right: true }; 6, 1, Oval { right: true }),
        two_steps!(0, 6, Oval { right: true }; 6, 12, Oval { right: true }),
        two_steps!(12, 20, Oval { right: false }; 6, 26, Oval { right: false }),
        two_steps!(0, 20, Oval { right: false }; 6, 12, Oval { right: false }),
        two_steps!(1, 23, Break; 10, 23, Control),
        two_steps!(12, 7, Outline { thick: true, update: true }; 6, 2, Oval { right: true }),
        two_steps!(0, 8, Oval { right: true }; 6, 13, Oval { right: true }),
        two_steps!(12, 13, Outline { thick: true, update: false }; 6, 6, Break),
        two_steps!(6, 8, Outline { thick: true, update: true }; 6, 22, Break),
        two_steps!(6, 23, Outline { thick: true, update: true }; 7, 6, Break),
        two_steps!(7, 7, Outline { thick: true, update: true }; 8, 23, Break),
        two_steps!(5, 27, Outline { thick: false, update: true }; 12, 5, Break),
        two_steps!(0, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 10, Break; 12, 10, Outline { thick: false, update: true }),
        two_steps!(0, 14, Break; 12, 14, Outline { thick: false, update: true }),
        two_steps!(0, 5, Break; 12, 14, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 5, Break),
        two_steps!(2, 2, Control; 6, 1, Outline { thick: true, update: true }),
        two_steps!(11, 3, Control; 10, 8, Outline { thick: true, update: true }),
        two_steps!(6, 11, Control; 6, 15, Outline { thick: true, update: true }),
        two_steps!(6, 24, Break; 6, 26, Outline { thick: true, update: true }),
        two_steps!(8, 8, Break; 8, 18, Outline { thick: false, update: false }),
        two_steps!(4, 9, Control; 3, 12, Outline { thick: false, update: true }),
        two_steps!(5, 16, Control; 9, 18, Outline { thick: false, update: true }),
        two_steps!(12, 16, Control; 13, 10, Outline { thick: false, update: true }),
        two_steps!(11, 6, Control; 6, 4, Outline { thick: false, update: true }),
        two_steps!(2, 6, Control; 0, 13, Outline { thick: false, update: true }),
        two_steps!(4, 23, Control; 13, 24, Outline { thick: false, update: true }),
        two_steps!(0, 24, Break; 6, 2, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 2, 17, Break),
        two_steps!(10, 17, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 18, Oval { right: true }; 0, 12, Oval { right: true }),
        two_steps!(12, 6, Oval { right: true }; 0, 2, Oval { right: true }),
        two_steps!(12, 2, Break; 4, 4, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 4, 22, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 12, Oval { right: true }; 0, 2, Oval { right: true }),
        two_steps!(12, 2, Outline { thick: false, update: false }; 0, 12, Outline { thick: true, update: true }),
        two_steps!(9, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 2, Outline { thick: false, update: false }),
        two_steps!(0, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 3, Break),
        two_steps!(3, 5, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(12, 23, Oval { right: true }; 12, 12, Outline { thick: true, update: true }),
        two_steps!(7, 12, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 12, Outline { thick: false, update: true }),
        two_steps!(12, 2, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 2, Break; 9, 2, Outline { thick: false, update: true }),
        two_steps!(6, 2, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(10, 1, Break; 10, 15, Outline { thick: true, update: true }),
        two_steps!(5, 23, Oval { right: false }; 1, 20, Oval { right: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(12, 2, Outline { thick: false, update: false }; 12, 24, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 6, 14, Outline { thick: false, update: true }),
        two_steps!(12, 2, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(0, 13, Oval { right: true }; 6, 25, Oval { right: true }),
        two_steps!(12, 13, Oval { right: true }; 6, 2, Oval { right: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 8, Oval { right: false }),
        two_steps!(0, 15, Oval { right: false }; 15, 4, Control),
        two_steps!(0, 0, Break; 6, 20, Break),
        two_steps!(12, 26, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 8, Oval { right: false }; 0, 15, Oval { right: false }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 3, Break),
        two_steps!(3, 3, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(6, 13, Oval { right: true }; 12, 19, Oval { right: false }),
        two_steps!(6, 24, Oval { right: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 0, 14, Outline { thick: true, update: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 14, Oval { right: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 1, 24, Outline { thick: true, update: true }),
        two_steps!(6, 10, Outline { thick: true, update: true }; 11, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(6, 11, Outline { thick: true, update: true }; 12, 2, Outline { thick: true, update: false }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 2, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(9, 1, Break; 3, 1, Outline { thick: true, update: true }),
        two_steps!(3, 24, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(1, 2, Break; 11, 23, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 9, 1, Outline { thick: true, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 7, Break; 6, 2, Outline { thick: true, update: true }),
        two_steps!(9, 7, Outline { thick: true, update: true }; 0, 23, Break),
        two_steps!(12, 23, Outline { thick: true, update: true }; 4, 1, Break),
        two_steps!(8, 6, Outline { thick: true, update: true }; 0, 8, Break),
        two_steps!(7, 6, Oval { right: false }; 11, 8, Control),
        two_steps!(12, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(0, 19, Oval { right: true }; 3, 24, Control),
        two_steps!(13, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 18, Oval { right: true }; 0, 12, Oval { right: true }),
        two_steps!(12, 7, Break; 0, 16, Oval { right: true }),
        two_steps!(12, 24, Oval { right: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 17, Oval { right: false }),
        two_steps!(12, 11, Oval { right: false }; 0, 17, Break),
        two_steps!(12, 17, Outline { thick: true, update: true }; 6, 10, Oval { right: true }),
        two_steps!(0, 17, Oval { right: true }; 8, 24, Oval { right: true }),
        two_steps!(12, 24, Outline { thick: true, update: false }; 3, 24, Break),
        two_steps!(3, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(5, 5, Control; 10, 4, Outline { thick: true, update: true }),
        two_steps!(12, 22, Break; 0, 15, Oval { right: false }),
        two_steps!(12, 10, Oval { right: false }; 12, 25, Outline { thick: true, update: true }),
        two_steps!(7, 28, Control; 1, 26, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(9, 13, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 4, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(6, 4, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 25, Outline { thick: true, update: true }),
        two_steps!(5, 28, Control; 3, 29, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Break),
        two_steps!(12, 24, Outline { thick: true, update: false }; 12, 8, Outline { thick: false, update: true }),
        two_steps!(4, 1, Break; 7, 1, Outline { thick: false, update: true }),
        two_steps!(7, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 3, 7, Control),
        two_steps!(6, 13, Outline { thick: false, update: true }; 6, 24, Outline { thick: false, update: false }),
        two_steps!(10, 7, Control; 12, 24, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 10, Break; 9, 9, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(0, 15, Oval { right: true }; 6, 24, Oval { right: true }),
        two_steps!(12, 15, Oval { right: true }; 6, 7, Oval { right: true }),
        two_steps!(0, 7, Break; 0, 31, Outline { thick: true, update: false }),
        two_steps!(12, 15, Oval { right: false }; 0, 23, Oval { right: false }),
        two_steps!(12, 31, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 16, Oval { right: true }; 12, 24, Oval { right: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(3, 9, Control; 12, 8, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 3, 8, Control),
        two_steps!(1, 12, Outline { thick: false, update: true }; 3, 14, Control),
        two_steps!(6, 15, Outline { thick: true, update: true }; 10, 16, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 9, 23, Control),
        two_steps!(0, 24, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: false }),
        two_steps!(4, 21, Control; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 3, 21, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(12, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 6, 11, Outline { thick: false, update: true }),
        two_steps!(10, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 3, 20, Control),
        two_steps!(12, 22, Outline { thick: false, update: true }; 12, 7, Break),
        two_steps!(12, 22, Outline { thick: true, update: true }; 9, 28, Control),
        two_steps!(1, 29, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 7, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 8, 1, Break),
        two_steps!(6, 3, Control; 5, 7, Outline { thick: true, update: true }),
        two_steps!(5, 11, Control; 2, 13, Outline { thick: true, update: true }),
        two_steps!(5, 15, Control; 5, 19, Outline { thick: true, update: true }),
        two_steps!(6, 23, Control; 8, 25, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 6, 29, Outline { thick: false, update: true }),
        two_steps!(4, 1, Break; 6, 3, Control),
        two_steps!(7, 7, Outline { thick: true, update: true }; 7, 11, Control),
        two_steps!(9, 13, Outline { thick: true, update: true }; 7, 15, Control),
        two_steps!(7, 19, Outline { thick: true, update: true }; 6, 23, Control),
        two_steps!(4, 25, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(3, 10, Control; 6, 12, Outline { thick: false, update: true }),
        two_steps!(9, 14, Control; 12, 12, Outline { thick: false, update: true }),
    ]
};

pub const GLYPHS_LATIN_EXTRA : GlyphTable = GlyphTable {
    basechar: 'Ā',
    addr: &[0, 4, 8, 13, 18, 23, 28, 35, 39, 47, 52, 59, 63, 71, 76, 83, 89, 93, 97, 105, 109, 118, 123, 131, 135, 143, 148, 157, 162, 171, 176, 185, 190, 194, 198, 202, 206, 211, 219, 227, 234, 244, 250, 258, 262, 271, 276, 284, 290, 298, 300, 310, 320, 327, 334, 338, 342, 347, 352, 357, 361, 365, 369, 373, 377, 381, 386, 390, 394, 398, 402, 406, 411, 416, 423, 428, 434, 438, 442, 450, 455, 464, 470, 480, 493, 500, 504, 508, 512, 520, 525, 534, 538, 548, 553, 558, 563, 573, 578, 584, 589, 596, 600, 605, 609, 615, 621, 625, 629, 634, 639, 650, 661, 667, 673, 678, 683, 688, 693, 698, 703, 709, 715, 719, 725, 729, 736, 741],
    data: &[
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(3, 0, Break; 9, 0, Outline { thick: false, update: true }),
        two_steps!(1, 6, Control; 0, 0, Break),
        two_steps!(3, 4, Break; 9, 4, Outline { thick: false, update: true }),
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(3, 0, Break; 6, 2, Control),
        two_steps!(9, 0, Outline { thick: false, update: false }; 1, 6, Control),
        two_steps!(0, 0, Break; 3, 2, Break),
        two_steps!(6, 4, Control; 9, 2, Outline { thick: false, update: true }),
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(12, 24, Break; 9, 27, Control),
        two_steps!(12, 29, Outline { thick: false, update: false }; 1, 6, Control),
        two_steps!(0, 0, Break; 14, 24, Break),
        two_steps!(9, 27, Control; 14, 29, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 3, 6, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 3, 22, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 9, 0, Break),
        two_steps!(6, 3, Outline { thick: false, update: true }; 3, 6, Control),
        two_steps!(0, 0, Break; 8, 1, Break),
        two_steps!(5, 5, Outline { thick: false, update: true }; 12, 4, Break),
        two_steps!(3, 6, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(3, 22, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 3, Break; 6, 0, Outline { thick: false, update: true }),
        two_steps!(10, 3, Outline { thick: false, update: true }; 3, 6, Control),
        two_steps!(0, 0, Break; 2, 5, Break),
        two_steps!(6, 2, Outline { thick: false, update: true }; 10, 5, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 3, 6, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 3, 22, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(7, 1, Outline { thick: true, update: true }; 3, 6, Control),
        two_steps!(0, 0, Break; 6, 5, Break),
        two_steps!(7, 5, Outline { thick: true, update: true }; 12, 4, Break),
        two_steps!(3, 6, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(3, 22, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 0, Break; 6, 3, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 3, 6, Control),
        two_steps!(0, 0, Break; 3, 4, Break),
        two_steps!(7, 6, Control; 11, 4, Outline { thick: false, update: true }),
        two_steps!(0, 3, Break; 12, 13, Oval { right: false }),
        two_steps!(0, 24, Oval { right: false }; 0, 3, Outline { thick: true, update: false }),
        two_steps!(2, 0, Break; 6, 2, Control),
        two_steps!(10, 0, Outline { thick: false, update: true }; 10, 1, Break),
        two_steps!(10, 24, Outline { thick: true, update: true }; 0, 17, Oval { right: false }),
        two_steps!(10, 12, Oval { right: false }; 13, 0, Break),
        two_steps!(13, 7, Outline { thick: true, update: true }; 4, 4, Control),
        two_steps!(0, 0, Break; 0, 12, Break),
        two_steps!(6, 12, Outline { thick: true, update: true }; 4, 6, Control),
        two_steps!(0, 0, Break; 9, 4, Break),
        two_steps!(15, 4, Outline { thick: false, update: true }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: false, update: false }; 0, 12, Outline { thick: false, update: true }),
        two_steps!(10, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 0, Break),
        two_steps!(9, 0, Outline { thick: false, update: true }; 5, 6, Control),
        two_steps!(0, 0, Break; 3, 6, Break),
        two_steps!(9, 6, Outline { thick: false, update: true }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: false, update: false }; 0, 12, Outline { thick: false, update: true }),
        two_steps!(10, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 0, Break),
        two_steps!(6, 3, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(5, 6, Control; 0, 0, Break),
        two_steps!(2, 6, Break; 6, 8, Control),
        two_steps!(10, 6, Outline { thick: false, update: true }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: false, update: false }; 0, 12, Outline { thick: false, update: true }),
        two_steps!(10, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 0, Break),
        two_steps!(7, 0, Outline { thick: true, update: true }; 5, 6, Control),
        two_steps!(0, 0, Break; 6, 5, Break),
        two_steps!(7, 5, Outline { thick: true, update: true }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: false, update: false }; 0, 12, Outline { thick: false, update: true }),
        two_steps!(10, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 9, 27, Control),
        two_steps!(12, 28, Outline { thick: true, update: true }; 5, 6, Control),
        two_steps!(0, 0, Break; 11, 24, Break),
        two_steps!(8, 27, Control; 12, 29, Outline { thick: false, update: true }),
        two_steps!(0, 4, Break; 12, 4, Outline { thick: false, update: false }),
        two_steps!(0, 12, Outline { thick: false, update: true }; 10, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 0, Break; 6, 3, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 5, 6, Control),
        two_steps!(0, 0, Break; 2, 4, Break),
        two_steps!(6, 6, Control; 10, 4, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 3, 6, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 12, 23, Oval { right: true }),
        two_steps!(12, 12, Outline { thick: true, update: true }; 7, 12, Outline { thick: false, update: true }),
        two_steps!(2, 3, Break; 6, 0, Outline { thick: false, update: true }),
        two_steps!(10, 3, Outline { thick: false, update: true }; 7, 6, Control),
        two_steps!(0, 0, Break; 2, 7, Break),
        two_steps!(6, 4, Outline { thick: false, update: true }; 10, 7, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 3, 6, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 12, 23, Oval { right: true }),
        two_steps!(12, 12, Outline { thick: true, update: true }; 7, 12, Outline { thick: false, update: true }),
        two_steps!(3, 0, Break; 6, 3, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 7, 6, Control),
        two_steps!(0, 0, Break; 3, 5, Break),
        two_steps!(6, 8, Control; 9, 5, Outline { thick: false, update: true }),
        two_steps!(7, 4, Control; 0, 0, Break),
        two_steps!(6, 1, Break; 7, 1, Outline { thick: true, update: true }),
        two_steps!(7, 6, Control; 0, 0, Break),
        two_steps!(6, 5, Break; 7, 5, Outline { thick: true, update: true }),
        two_steps!(7, 4, Control; 0, 0, Break),
        two_steps!(7, 25, Break; 6, 27, Outline { thick: false, update: true }),
        two_steps!(7, 6, Control; 0, 0, Break),
        two_steps!(7, 4, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(8, 4, Control; 0, 0, Break),
        two_steps!(3, 3, Break; 6, 0, Outline { thick: false, update: true }),
        two_steps!(9, 3, Outline { thick: false, update: true }; 2, 4, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 2, 12, Break),
        two_steps!(10, 13, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 4, Break; 2, 1, Outline { thick: false, update: true }),
        two_steps!(5, 4, Outline { thick: false, update: true }; 2, 1, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 2, 12, Break),
        two_steps!(11, 12, Outline { thick: false, update: true }; 11, 1, Break),
        two_steps!(11, 24, Outline { thick: true, update: true }; 0, 5, Break),
        two_steps!(14, 5, Outline { thick: false, update: true }; 2, 1, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 2, 12, Break),
        two_steps!(10, 13, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 4, Break; 4, 4, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 9, 4, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(2, 2, Break; 4, 0, Outline { thick: false, update: true }),
        two_steps!(7, 3, Outline { thick: false, update: true }; 10, 0, Outline { thick: false, update: true }),
        two_steps!(6, 6, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 5, 1, Outline { thick: false, update: true }),
        two_steps!(7, 3, Outline { thick: false, update: true }; 9, 1, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 9, 4, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(2, 2, Break; 10, 2, Outline { thick: false, update: true }),
        two_steps!(6, 6, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 9, 3, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 9, 4, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(2, 1, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 1, Outline { thick: false, update: true }; 6, 6, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 3, Break),
        two_steps!(6, 5, Outline { thick: false, update: true }; 9, 3, Outline { thick: false, update: true }),
        two_steps!(3, 1, Break; 9, 1, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(5, 29, Control; 9, 29, Outline { thick: false, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(6, 28, Control; 9, 27, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 9, 4, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(6, 2, Break; 7, 2, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(2, 1, Break; 8, 1, Outline { thick: false, update: true }),
        two_steps!(5, 1, Break; 5, 24, Outline { thick: true, update: true }),
        two_steps!(2, 24, Break; 8, 24, Outline { thick: false, update: true }),
        two_steps!(10, 1, Break; 10, 20, Outline { thick: true, update: true }),
        two_steps!(8, 27, Control; 3, 23, Outline { thick: true, update: true }),
        two_steps!(3, 4, Break; 3, 5, Outline { thick: true, update: true }),
        two_steps!(3, 11, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(6, 4, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 25, Outline { thick: true, update: true }),
        two_steps!(6, 29, Control; 3, 29, Outline { thick: true, update: true }),
        two_steps!(10, 5, Break; 10, 20, Outline { thick: true, update: true }),
        two_steps!(7, 25, Control; 3, 23, Outline { thick: true, update: true }),
        two_steps!(7, 3, Break; 10, 1, Outline { thick: false, update: true }),
        two_steps!(14, 3, Outline { thick: false, update: true }; 6, 11, Break),
        two_steps!(6, 25, Outline { thick: true, update: true }; 5, 28, Control),
        two_steps!(3, 29, Outline { thick: true, update: true }; 3, 10, Break),
        two_steps!(6, 7, Outline { thick: false, update: true }; 9, 10, Outline { thick: false, update: true }),
        two_steps!(11, 4, Control; 0, 0, Break),
        two_steps!(7, 24, Break; 4, 28, Outline { thick: false, update: true }),
        two_steps!(11, 6, Control; 0, 0, Break),
        two_steps!(7, 24, Break; 4, 28, Outline { thick: false, update: true }),
        two_steps!(0, 8, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 24, Outline { thick: true, update: false }),
        two_steps!(12, 8, Outline { thick: false, update: true }; 0, 8, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(3, 0, Break; 0, 4, Outline { thick: false, update: true }),
        two_steps!(4, 5, Break; 7, 5, Outline { thick: false, update: true }),
        two_steps!(7, 24, Outline { thick: false, update: true }; 7, 0, Break),
        two_steps!(5, 2, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 7, 26, Break),
        two_steps!(5, 29, Outline { thick: false, update: true }; 12, 6, Control),
        two_steps!(0, 0, Break; 9, 25, Break),
        two_steps!(6, 29, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 5, 2, Break),
        two_steps!(3, 6, Outline { thick: false, update: true }; 12, 6, Control),
        two_steps!(0, 0, Break; 11, 1, Break),
        two_steps!(10, 5, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 4, 11, Break),
        two_steps!(4, 12, Outline { thick: true, update: true }; 12, 6, Control),
        two_steps!(0, 0, Break; 10, 12, Break),
        two_steps!(10, 13, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 11, Break; 1, 13, Outline { thick: false, update: true }),
        two_steps!(12, 6, Control; 0, 0, Break),
        two_steps!(10, 8, Break; 5, 13, Outline { thick: false, update: true }),
        two_steps!(14, 4, Control; 0, 0, Break),
        two_steps!(8, 0, Break; 6, 4, Outline { thick: false, update: true }),
        two_steps!(14, 6, Control; 0, 0, Break),
        two_steps!(8, 2, Break; 5, 6, Outline { thick: false, update: true }),
        two_steps!(14, 4, Control; 0, 0, Break),
        two_steps!(8, 23, Break; 5, 27, Outline { thick: false, update: true }),
        two_steps!(14, 6, Control; 0, 0, Break),
        two_steps!(7, 22, Break; 5, 28, Outline { thick: false, update: true }),
        two_steps!(14, 4, Control; 0, 0, Break),
        two_steps!(3, 1, Break; 6, 4, Outline { thick: false, update: true }),
        two_steps!(9, 1, Outline { thick: false, update: true }; 14, 6, Control),
        two_steps!(0, 0, Break; 3, 4, Break),
        two_steps!(6, 6, Outline { thick: false, update: true }; 9, 4, Outline { thick: false, update: true }),
        two_steps!(2, 7, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 10, Break; 10, 11, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 2, 2, Break),
        two_steps!(0, 6, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 1, Outline { thick: true, update: false }),
        two_steps!(10, 29, Control; 3, 30, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 10, Break; 9, 11, Control),
        two_steps!(12, 21, Outline { thick: true, update: true }; 5, 30, Oval { right: false }),
        two_steps!(15, 4, Control; 0, 0, Break),
        two_steps!(2, 0, Break; 10, 0, Outline { thick: false, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(2, 2, Break; 10, 2, Outline { thick: false, update: true }),
        two_steps!(6, 3, Break; 0, 13, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 13, Oval { right: true }),
        two_steps!(6, 3, Oval { right: true }; 3, 0, Break),
        two_steps!(6, 2, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(3, 2, Break; 6, 5, Control),
        two_steps!(9, 2, Outline { thick: false, update: true }; 6, 3, Break),
        two_steps!(0, 13, Oval { right: true }; 6, 24, Oval { right: true }),
        two_steps!(12, 13, Oval { right: true }; 6, 3, Oval { right: true }),
        two_steps!(7, 0, Break; 5, 2, Outline { thick: false, update: true }),
        two_steps!(11, 0, Break; 9, 2, Outline { thick: false, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(6, 3, Break; 5, 6, Outline { thick: false, update: true }),
        two_steps!(9, 3, Break; 8, 6, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 12, 1, Outline { thick: true, update: false }),
        two_steps!(6, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(2, 21, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(2, 3, Control; 6, 1, Outline { thick: true, update: true }),
        two_steps!(6, 17, Break; 12, 17, Outline { thick: false, update: true }),
        two_steps!(11, 12, Control; 9, 10, Outline { thick: false, update: true }),
        two_steps!(7, 12, Control; 6, 17, Outline { thick: false, update: true }),
        two_steps!(3, 10, Control; 0, 17, Outline { thick: false, update: true }),
        two_steps!(3, 24, Control; 6, 17, Outline { thick: false, update: true }),
        two_steps!(7, 22, Control; 9, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 0, 3, Break),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 9, Oval { right: false }),
        two_steps!(0, 14, Oval { right: false }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(8, 0, Break; 5, 2, Outline { thick: false, update: true }),
        two_steps!(2, 7, Control; 0, 0, Break),
        two_steps!(8, 2, Break; 6, 6, Outline { thick: false, update: true }),
        two_steps!(2, 5, Control; 0, 0, Break),
        two_steps!(7, 23, Break; 5, 27, Outline { thick: false, update: false }),
        two_steps!(2, 7, Control; 0, 0, Break),
        two_steps!(7, 24, Break; 5, 27, Outline { thick: false, update: true }),
        two_steps!(0, 3, Break; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 9, Oval { right: false }; 0, 14, Oval { right: false }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 3, 0, Break),
        two_steps!(6, 2, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(2, 7, Control; 0, 0, Break),
        two_steps!(4, 2, Break; 7, 5, Control),
        two_steps!(10, 2, Outline { thick: false, update: true }; 12, 4, Break),
        two_steps!(3, 4, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(6, 13, Oval { right: true }; 12, 19, Oval { right: false }),
        two_steps!(6, 24, Oval { right: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(8, 0, Break; 5, 3, Outline { thick: false, update: true }),
        two_steps!(3, 7, Control; 0, 0, Break),
        two_steps!(9, 2, Break; 6, 5, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 3, 4, Control),
        two_steps!(0, 7, Outline { thick: false, update: true }; 6, 13, Oval { right: true }),
        two_steps!(12, 19, Oval { right: false }; 6, 24, Oval { right: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 2, 3, Break),
        two_steps!(6, 0, Outline { thick: false, update: true }; 10, 3, Outline { thick: false, update: true }),
        two_steps!(3, 7, Control; 0, 0, Break),
        two_steps!(2, 6, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 6, Outline { thick: false, update: true }; 3, 5, Control),
        two_steps!(0, 0, Break; 6, 24, Break),
        two_steps!(7, 28, Control; 3, 28, Outline { thick: false, update: false }),
        two_steps!(3, 7, Control; 0, 0, Break),
        two_steps!(6, 24, Break; 8, 28, Control),
        two_steps!(3, 28, Outline { thick: false, update: false }; 12, 4, Break),
        two_steps!(3, 4, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(6, 13, Oval { right: true }; 12, 19, Oval { right: false }),
        two_steps!(6, 24, Oval { right: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(2, 0, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 0, Outline { thick: false, update: true }; 3, 7, Control),
        two_steps!(0, 0, Break; 3, 2, Break),
        two_steps!(7, 5, Control; 11, 2, Outline { thick: false, update: false }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 6, 23, Break),
        two_steps!(7, 28, Control; 3, 28, Outline { thick: false, update: false }),
        two_steps!(4, 7, Control; 0, 0, Break),
        two_steps!(6, 23, Break; 8, 27, Control),
        two_steps!(4, 27, Outline { thick: false, update: false }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: true, update: true }; 6, 4, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 2, 0, Break),
        two_steps!(6, 3, Outline { thick: false, update: true }; 10, 0, Outline { thick: false, update: true }),
        two_steps!(4, 7, Control; 0, 0, Break),
        two_steps!(12, 1, Break; 10, 5, Outline { thick: false, update: false }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 3, 11, Break),
        two_steps!(9, 11, Outline { thick: false, update: false }; 4, 7, Control),
        two_steps!(0, 0, Break; 3, 11, Break),
        two_steps!(9, 11, Outline { thick: false, update: false }; 5, 5, Control),
        two_steps!(0, 0, Break; 3, 3, Break),
        two_steps!(5, 1, Outline { thick: false, update: true }; 7, 3, Outline { thick: false, update: true }),
        two_steps!(9, 1, Outline { thick: false, update: true }; 5, 7, Control),
        two_steps!(0, 0, Break; 3, 7, Break),
        two_steps!(5, 5, Outline { thick: false, update: true }; 7, 7, Outline { thick: false, update: true }),
        two_steps!(9, 5, Outline { thick: false, update: true }; 5, 5, Control),
        two_steps!(0, 0, Break; 4, 2, Break),
        two_steps!(8, 2, Outline { thick: false, update: true }; 5, 7, Control),
        two_steps!(0, 0, Break; 2, 2, Break),
        two_steps!(10, 2, Outline { thick: false, update: true }; 5, 5, Control),
        two_steps!(0, 0, Break; 3, 0, Break),
        two_steps!(6, 2, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(5, 7, Control; 0, 0, Break),
        two_steps!(3, 0, Break; 6, 2, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 5, 5, Control),
        two_steps!(0, 0, Break; 6, 0, Break),
        two_steps!(4, 1, Control; 3, 3, Outline { thick: false, update: true }),
        two_steps!(4, 5, Control; 6, 6, Outline { thick: false, update: true }),
        two_steps!(8, 5, Control; 9, 3, Outline { thick: false, update: true }),
        two_steps!(8, 1, Control; 6, 0, Outline { thick: false, update: true }),
        two_steps!(5, 7, Control; 0, 0, Break),
        two_steps!(6, 0, Break; 4, 1, Control),
        two_steps!(3, 3, Outline { thick: false, update: true }; 4, 5, Control),
        two_steps!(6, 6, Outline { thick: false, update: true }; 8, 5, Control),
        two_steps!(9, 3, Outline { thick: false, update: true }; 8, 1, Control),
        two_steps!(6, 0, Outline { thick: false, update: true }; 5, 5, Control),
        two_steps!(0, 0, Break; 7, 0, Break),
        two_steps!(5, 2, Outline { thick: false, update: true }; 11, 0, Break),
        two_steps!(9, 2, Outline { thick: false, update: true }; 5, 7, Control),
        two_steps!(0, 0, Break; 6, 3, Break),
        two_steps!(5, 6, Outline { thick: false, update: true }; 9, 3, Break),
        two_steps!(8, 6, Outline { thick: false, update: true }; 5, 5, Control),
        two_steps!(0, 0, Break; 5, 25, Break),
        two_steps!(5, 29, Control; 9, 29, Outline { thick: false, update: true }),
        two_steps!(5, 7, Control; 0, 0, Break),
        two_steps!(8, 24, Break; 5, 28, Control),
        two_steps!(9, 29, Outline { thick: false, update: true }; 7, 5, Control),
        two_steps!(0, 0, Break; 2, 3, Break),
        two_steps!(6, 0, Outline { thick: false, update: true }; 10, 3, Outline { thick: false, update: true }),
        two_steps!(7, 7, Control; 0, 0, Break),
        two_steps!(2, 6, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 6, Outline { thick: false, update: true }; 9, 5, Control),
        two_steps!(0, 0, Break; 2, 3, Break),
        two_steps!(6, 0, Outline { thick: false, update: true }; 10, 3, Outline { thick: false, update: true }),
        two_steps!(9, 7, Control; 0, 0, Break),
        two_steps!(2, 6, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 6, Outline { thick: false, update: true }; 9, 5, Control),
        two_steps!(0, 0, Break; 4, 0, Break),
        two_steps!(4, 1, Outline { thick: true, update: false }; 8, 0, Break),
        two_steps!(8, 1, Outline { thick: true, update: false }; 0, 3, Break),
        two_steps!(12, 3, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 8, 0, Break),
        two_steps!(5, 3, Outline { thick: false, update: false }; 10, 7, Control),
        two_steps!(0, 0, Break; 8, 2, Break),
        two_steps!(5, 5, Outline { thick: false, update: false }; 0, 3, Break),
        two_steps!(12, 3, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 0, Break),
        two_steps!(7, 0, Outline { thick: true, update: false }; 10, 7, Control),
        two_steps!(0, 0, Break; 6, 5, Break),
        two_steps!(7, 5, Outline { thick: true, update: true }; 0, 4, Break),
        two_steps!(12, 4, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 0, Break),
        two_steps!(6, 3, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(10, 7, Control; 0, 0, Break),
        two_steps!(3, 3, Break; 6, 6, Control),
        two_steps!(9, 3, Outline { thick: false, update: true }; 9, 3, Break),
        two_steps!(5, 8, Control; 4, 27, Outline { thick: true, update: true }),
    ]
};

pub const GLYPHS_GREEK : GlyphTable = GlyphTable {
    basechar: 'Ͱ',
    addr: &[0, 3, 7, 12, 18, 20, 22, 25, 29, 29, 29, 31, 36, 43, 50, 54, 58, 58, 58, 58, 58, 60, 66, 70, 72, 80, 88, 96, 96, 100, 100, 106, 110, 114, 116, 118, 121, 125, 127, 129, 131, 135, 137, 139, 142, 144, 146, 151, 153, 156, 158, 158, 162, 165, 167, 173, 175, 179, 186, 196, 202, 206, 210, 214, 218, 222, 229, 239, 243, 253, 258, 264, 270, 277, 280, 285, 291, 299, 303, 312, 314, 321, 328, 333, 340, 345, 350, 356, 360, 367, 374, 380, 386, 390, 394, 398],
    data: &[
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(12, 12, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Outline { thick: true, update: true }),
        two_steps!(11, 15, Outline { thick: true, update: true }; 0, 7, Outline { thick: false, update: false }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 12, 7, Outline { thick: false, update: true }),
        two_steps!(6, 2, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 7, Break; 3, 3, Outline { thick: false, update: true }),
        two_steps!(9, 3, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: true }),
        two_steps!(6, 3, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(7, 4, Break; 5, 6, Outline { thick: true, update: true }),
        two_steps!(7, 23, Break; 5, 26, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 23, Break),
        two_steps!(8, 26, Outline { thick: true, update: true }; 0, 6, Break),
        two_steps!(8, 8, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(8, 22, Control; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 3, 9, Control),
        two_steps!(0, 16, Outline { thick: true, update: true }; 3, 23, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 16, Break),
        two_steps!(8, 16, Outline { thick: true, update: true }; 0, 6, Break),
        two_steps!(8, 8, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(8, 22, Control; 0, 24, Outline { thick: true, update: true }),
        two_steps!(5, 15, Break; 7, 15, Outline { thick: true, update: true }),
        two_steps!(7, 6, Break; 7, 7, Outline { thick: true, update: true }),
        two_steps!(8, 23, Break; 5, 27, Outline { thick: false, update: true }),
        two_steps!(10, 1, Break; 10, 20, Outline { thick: true, update: true }),
        two_steps!(8, 27, Control; 5, 26, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 6, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 6, Outline { thick: true, update: true }),
        two_steps!(2, 9, Break; 4, 9, Outline { thick: true, update: true }),
        two_steps!(8, 9, Break; 10, 9, Outline { thick: true, update: true }),
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(4, 1, Break; 1, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 13, Outline { thick: true, update: true }),
        two_steps!(12, 3, Break; 2, 3, Outline { thick: true, update: true }),
        two_steps!(2, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(2, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 1, 5, Outline { thick: true, update: true }),
        two_steps!(2, 3, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 12, Break; 12, 12, Outline { thick: false, update: true }),
        two_steps!(12, 3, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 1, Break; 0, 5, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 9, 1, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(2, 1, Break; 0, 5, Outline { thick: true, update: true }),
        two_steps!(15, 4, Control; 0, 0, Break),
        two_steps!(3, 1, Break; 0, 4, Outline { thick: false, update: false }),
        two_steps!(2, 4, Break; 7, 11, Outline { thick: true, update: true }),
        two_steps!(12, 4, Outline { thick: true, update: false }; 7, 24, Outline { thick: true, update: true }),
        two_steps!(2, 1, Break; 0, 6, Outline { thick: false, update: false }),
        two_steps!(9, 26, Control; 1, 0, Break),
        two_steps!(3, 1, Break; 0, 5, Outline { thick: false, update: false }),
        two_steps!(5, 24, Control; 1, 0, Break),
        two_steps!(9, 27, Control; 1, 0, Break),
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(2, 4, Control; 0, 0, Break),
        two_steps!(12, 4, Break; 0, 4, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 1, Outline { thick: true, update: true }; 5, 4, Control),
        two_steps!(0, 0, Break; 10, 5, Control),
        two_steps!(0, 0, Break; 8, 4, Control),
        two_steps!(0, 0, Break; 15, 4, Control),
        two_steps!(0, 0, Break; 2, 12, Break),
        two_steps!(10, 12, Outline { thick: true, update: true }; 9, 4, Control),
        two_steps!(0, 0, Break; 11, 4, Control),
        two_steps!(0, 0, Break; 0, 24, Break),
        two_steps!(6, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(13, 4, Control; 0, 0, Break),
        two_steps!(14, 4, Control; 0, 0, Break),
        two_steps!(12, 2, Outline { thick: true, update: true }; 3, 10, Break),
        two_steps!(9, 10, Outline { thick: true, update: true }; 0, 24, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 15, 4, Control),
        two_steps!(0, 0, Break; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 5, Control; 0, 0, Break),
        two_steps!(12, 2, Outline { thick: true, update: false }; 8, 12, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 9, 5, Control),
        two_steps!(0, 0, Break; 6, 24, Break),
        two_steps!(6, 1, Outline { thick: true, update: true }; 0, 8, Oval { right: true }),
        two_steps!(6, 17, Oval { right: true }; 12, 8, Oval { right: true }),
        two_steps!(6, 1, Oval { right: true }; 8, 5, Control),
        two_steps!(0, 0, Break; 6, 12, Oval { right: true }),
        two_steps!(12, 2, Oval { right: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 0, 24, Break),
        two_steps!(4, 24, Outline { thick: true, update: true }; 0, 14, Oval { right: false }),
        two_steps!(6, 2, Oval { right: false }; 12, 14, Oval { right: false }),
        two_steps!(8, 24, Oval { right: false }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 9, 3, Outline { thick: false, update: false }),
        two_steps!(6, 3, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(3, 0, Break; 4, 0, Outline { thick: true, update: true }),
        two_steps!(8, 0, Break; 9, 0, Outline { thick: true, update: true }),
        two_steps!(9, 5, Control; 0, 0, Break),
        two_steps!(4, 0, Break; 4, 1, Outline { thick: true, update: false }),
        two_steps!(8, 0, Break; 8, 1, Outline { thick: true, update: false }),
        two_steps!(1, 27, Control; 1, 0, Break),
        two_steps!(7, 3, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(5, 27, Control; 1, 0, Break),
        two_steps!(7, 2, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(7, 27, Control; 1, 0, Break),
        two_steps!(7, 2, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(9, 27, Control; 1, 0, Break),
        two_steps!(7, 2, Break; 5, 5, Outline { thick: false, update: true }),
        two_steps!(5, 28, Control; 1, 0, Break),
        two_steps!(5, 24, Control; 1, 0, Break),
        two_steps!(12, 7, Break; 9, 20, Control),
        two_steps!(4, 24, Outline { thick: true, update: true }; 0, 16, Oval { right: false }),
        two_steps!(4, 7, Oval { right: false }; 9, 11, Control),
        two_steps!(13, 24, Outline { thick: true, update: true }; 0, 31, Break),
        two_steps!(2, 4, Oval { right: false }; 8, 3, Control),
        two_steps!(12, 5, Outline { thick: true, update: true }; 11, 8, Control),
        two_steps!(5, 10, Outline { thick: true, update: true }; 10, 12, Control),
        two_steps!(12, 16, Outline { thick: true, update: true }; 9, 22, Control),
        two_steps!(1, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(6, 12, Outline { thick: true, update: true }; 10, 6, Outline { thick: true, update: false }),
        two_steps!(5, 23, Outline { thick: true, update: true }; 12, 5, Break),
        two_steps!(6, 4, Control; 3, 8, Outline { thick: true, update: true }),
        two_steps!(11, 15, Control; 12, 19, Outline { thick: true, update: true }),
        two_steps!(10, 23, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(2, 21, Control; 2, 17, Outline { thick: true, update: true }),
        two_steps!(8, 12, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 11, Oval { right: true }; 9, 15, Oval { right: true }),
        two_steps!(0, 19, Oval { right: true }; 12, 23, Oval { right: true }),
        two_steps!(12, 2, Outline { thick: true, update: true }; 1, 15, Outline { thick: true, update: true }),
        two_steps!(1, 23, Control; 8, 24, Outline { thick: true, update: true }),
        two_steps!(11, 27, Control; 8, 29, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 15, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 6, 7, Oval { right: false }),
        two_steps!(12, 22, Oval { right: false }; 12, 31, Outline { thick: true, update: false }),
        two_steps!(6, 1, Break; 2, 12, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 10, 12, Oval { right: true }),
        two_steps!(6, 1, Oval { right: true }; 2, 12, Break),
        two_steps!(10, 12, Outline { thick: false, update: true }; 6, 10, Break),
        two_steps!(7, 22, Control; 10, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 7, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 0, 24, Break),
        two_steps!(7, 12, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(6, 4, Outline { thick: true, update: true }; 3, 4, Control),
        two_steps!(2, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 16, Outline { thick: true, update: true }; 0, 31, Outline { thick: true, update: false }),
        two_steps!(2, 22, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(10, 21, Control; 12, 8, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(5, 24, Outline { thick: true, update: true }; 12, 14, Control),
        two_steps!(10, 7, Outline { thick: true, update: true }; 12, 2, Outline { thick: false, update: true }),
        two_steps!(3, 3, Control; 0, 6, Outline { thick: false, update: true }),
        two_steps!(4, 9, Control; 12, 11, Outline { thick: false, update: true }),
        two_steps!(0, 16, Oval { right: true }; 8, 21, Oval { right: true }),
        two_steps!(12, 23, Control; 9, 25, Outline { thick: false, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(2, 7, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(9, 7, Break; 9, 20, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 31, Break),
        two_steps!(0, 17, Control; 3, 11, Outline { thick: true, update: true }),
        two_steps!(8, 11, Control; 11, 15, Outline { thick: true, update: true }),
        two_steps!(8, 20, Control; 1, 21, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 15, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 11, 26, Control),
        two_steps!(10, 29, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(3, 9, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 18, Oval { right: true }),
        two_steps!(10, 12, Control; 3, 10, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 6, 21, Control),
        two_steps!(10, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(1, 20, Control; 4, 24, Outline { thick: true, update: true }),
        two_steps!(10, 20, Control; 12, 7, Outline { thick: true, update: true }),
        two_steps!(3, 7, Break; 0, 15, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 15, Oval { right: true }),
        two_steps!(6, 7, Oval { right: true }; 6, 31, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 29, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 29, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 2, 21, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 10, 21, Control),
        two_steps!(12, 7, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(6, 31, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 20, Control; 2, 24, Outline { thick: true, update: true }),
        two_steps!(6, 12, Oval { right: true }; 9, 24, Oval { right: true }),
        two_steps!(12, 21, Control; 12, 7, Outline { thick: true, update: true }),
        two_steps!(9, 27, Control; 1, 0, Break),
        two_steps!(3, 1, Break; 3, 0, Outline { thick: true, update: true }),
        two_steps!(9, 1, Break; 9, 0, Outline { thick: true, update: true }),
        two_steps!(5, 28, Control; 1, 0, Break),
        two_steps!(3, 1, Break; 3, 0, Outline { thick: true, update: true }),
        two_steps!(9, 1, Break; 9, 0, Outline { thick: true, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(8, 2, Break; 5, 5, Outline { thick: false, update: true }),
        two_steps!(5, 28, Control; 1, 0, Break),
        two_steps!(7, 3, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(9, 28, Control; 1, 0, Break),
        two_steps!(7, 3, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(11, 4, Control; 0, 0, Break),
        two_steps!(12, 24, Break; 11, 28, Control),
        two_steps!(7, 28, Outline { thick: false, update: true }; 0, 0, Break),
    ]
};

pub const GLYPHS_CYRILLIC : GlyphTable = GlyphTable {
    basechar: 'Ѐ',
    addr: &[0, 8, 18, 25, 29, 34, 36, 38, 40, 42, 50, 57, 63, 69, 74, 79, 84, 86, 90, 92, 94, 102, 104, 109, 111, 113, 118, 120, 126, 128, 130, 132, 134, 136, 138, 140, 146, 148, 150, 155, 159, 164, 171, 175, 180, 183, 186, 193, 198, 200, 209, 215, 218, 226, 228, 234, 239, 241, 246, 248, 255, 260, 266, 268, 272, 274, 276, 280, 282, 288, 290, 296, 301, 307, 315, 320, 326, 330, 334, 342, 347, 351, 357, 365, 369, 373, 375, 379, 385, 387, 396, 404, 411, 415, 419, 424],
    data: &[
        two_steps!(0, 4, Break; 12, 4, Outline { thick: true, update: false }),
        two_steps!(0, 14, Outline { thick: true, update: true }; 9, 14, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 0, Break; 7, 3, Outline { thick: false, update: false }),
        two_steps!(0, 4, Break; 12, 4, Outline { thick: true, update: false }),
        two_steps!(0, 14, Outline { thick: true, update: true }; 9, 14, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 3, 1, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 9, 1, Outline { thick: true, update: true }),
        two_steps!(6, 2, Outline { thick: false, update: true }; 3, 2, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 3, 12, Break),
        two_steps!(12, 16, Oval { right: false }; 12, 22, Outline { thick: true, update: true }),
        two_steps!(7, 27, Oval { right: false }; 3, 25, Control),
        two_steps!(1, 0, Break; 7, 0, Break),
        two_steps!(5, 3, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(0, 12, Oval { right: true }; 12, 24, Oval { right: true }),
        two_steps!(0, 12, Break; 10, 12, Outline { thick: true, update: true }),
        two_steps!(3, 5, Control; 0, 0, Break),
        two_steps!(9, 4, Control; 0, 0, Break),
        two_steps!(10, 26, Control; 1, 0, Break),
        two_steps!(10, 4, Control; 0, 0, Break),
        two_steps!(0, 21, Break; 2, 24, Oval { right: true }),
        two_steps!(4, 14, Control; 3, 1, Outline { thick: true, update: true }),
        two_steps!(8, 1, Outline { thick: true, update: true }; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 18, Oval { right: true }; 8, 11, Oval { right: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(7, 12, Outline { thick: true, update: true }; 7, 1, Break),
        two_steps!(7, 24, Outline { thick: true, update: true }; 12, 18, Oval { right: true }),
        two_steps!(7, 12, Oval { right: true }; 6, 2, Outline { thick: true, update: true }),
        two_steps!(3, 2, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 12, Break; 10, 12, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 1, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 7, 0, Break),
        two_steps!(5, 3, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 0, Break; 7, 4, Outline { thick: false, update: true }),
        two_steps!(3, 2, Control; 2, 0, Break),
        two_steps!(3, 0, Break; 6, 3, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(6, 24, Break; 6, 28, Outline { thick: true, update: true }),
        two_steps!(1, 4, Control; 0, 0, Break),
        two_steps!(12, 2, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 17, Oval { right: true }; 0, 10, Oval { right: true }),
        two_steps!(2, 4, Control; 0, 0, Break),
        two_steps!(3, 25, Control; 1, 0, Break),
        two_steps!(3, 24, Break; 3, 1, Outline { thick: true, update: true }),
        two_steps!(9, 1, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 29, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 29, Outline { thick: true, update: true }),
        two_steps!(5, 4, Control; 0, 0, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 2, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 2, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 3, 3, Control),
        two_steps!(0, 0, Break; 6, 23, Control),
        two_steps!(1, 0, Break; 6, 23, Control),
        two_steps!(1, 0, Break; 4, 1, Break),
        two_steps!(6, 3, Control; 8, 1, Outline { thick: false, update: false }),
        two_steps!(11, 4, Control; 0, 0, Break),
        two_steps!(0, 21, Break; 2, 24, Oval { right: true }),
        two_steps!(4, 17, Control; 4, 1, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(13, 4, Control; 0, 0, Break),
        two_steps!(8, 4, Control; 0, 0, Break),
        two_steps!(15, 4, Control; 0, 0, Break),
        two_steps!(0, 26, Control; 1, 0, Break),
        two_steps!(0, 5, Control; 0, 0, Break),
        two_steps!(3, 4, Control; 0, 0, Break),
        two_steps!(4, 5, Control; 0, 0, Break),
        two_steps!(3, 14, Control; 10, 17, Outline { thick: true, update: true }),
        two_steps!(12, 1, Break; 10, 19, Control),
        two_steps!(3, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(6, 26, Control; 1, 0, Break),
        two_steps!(8, 5, Control; 0, 0, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(9, 2, Outline { thick: true, update: false }; 13, 24, Outline { thick: true, update: true }),
        two_steps!(13, 28, Outline { thick: true, update: true }; 3, 12, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 7, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 5, 24, Outline { thick: true, update: true }),
        two_steps!(5, 7, Outline { thick: false, update: false }; 10, 24, Outline { thick: true, update: true }),
        two_steps!(10, 1, Outline { thick: false, update: false }; 13, 24, Outline { thick: true, update: true }),
        two_steps!(13, 28, Outline { thick: false, update: false }; 3, 2, Outline { thick: true, update: true }),
        two_steps!(3, 24, Outline { thick: true, update: true }; 12, 17, Oval { right: true }),
        two_steps!(3, 10, Oval { right: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(8, 18, Oval { right: true }; 0, 11, Oval { right: true }),
        two_steps!(12, 2, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 18, Oval { right: true }),
        two_steps!(0, 11, Oval { right: true }; 12, 12, Oval { right: false }),
        two_steps!(1, 12, Outline { thick: false, update: false }; 0, 24, Oval { right: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(4, 12, Outline { thick: true, update: true }; 8, 24, Oval { right: true }),
        two_steps!(12, 12, Oval { right: true }; 8, 1, Oval { right: true }),
        two_steps!(4, 12, Oval { right: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: false }; 0, 6, Oval { right: true }),
        two_steps!(12, 12, Oval { right: true }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(1, 6, Control; 0, 0, Break),
        two_steps!(12, 1, Break; 3, 3, Control),
        two_steps!(1, 7, Outline { thick: true, update: true }; 1, 18, Control),
        two_steps!(3, 24, Outline { thick: true, update: true }; 10, 23, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 9, 13, Control),
        two_steps!(1, 14, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 19, Oval { right: true }),
        two_steps!(0, 15, Oval { right: true }; 12, 11, Oval { right: true }),
        two_steps!(0, 7, Oval { right: true }; 0, 7, Break),
        two_steps!(12, 7, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(3, 24, Break; 3, 7, Outline { thick: true, update: true }),
        two_steps!(9, 7, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 29, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 29, Outline { thick: true, update: true }),
        two_steps!(5, 6, Control; 0, 0, Break),
        two_steps!(0, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 10, Oval { right: false }),
        two_steps!(4, 15, Oval { right: false }; 12, 20, Oval { right: false }),
        two_steps!(0, 24, Oval { right: false }; 7, 23, Control),
        two_steps!(1, 0, Break; 7, 23, Control),
        two_steps!(1, 0, Break; 4, 6, Break),
        two_steps!(6, 9, Control; 8, 6, Outline { thick: true, update: true }),
        two_steps!(10, 27, Control; 1, 0, Break),
        two_steps!(0, 22, Break; 1, 23, Control),
        two_steps!(3, 24, Outline { thick: true, update: true }; 4, 19, Control),
        two_steps!(3, 7, Outline { thick: true, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: false }; 6, 16, Outline { thick: false, update: true }),
        two_steps!(12, 7, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 15, Outline { thick: false, update: true }),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(15, 6, Control; 0, 0, Break),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 7, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Control; 0, 0, Break),
        two_steps!(3, 6, Control; 0, 0, Break),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(9, 7, Control; 0, 0, Break),
        two_steps!(6, 7, Break; 0, 15, Oval { right: true }),
        two_steps!(6, 24, Oval { right: true }; 12, 15, Oval { right: true }),
        two_steps!(6, 7, Oval { right: true }; 6, 31, Outline { thick: true, update: true }),
        two_steps!(8, 7, Control; 0, 0, Break),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 9, 7, Outline { thick: true, update: false }),
        two_steps!(13, 24, Outline { thick: true, update: true }; 13, 28, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 3, 15, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 24, Outline { thick: true, update: true }),
        two_steps!(6, 12, Outline { thick: false, update: false }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Outline { thick: false, update: false }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 5, 24, Outline { thick: true, update: true }),
        two_steps!(5, 13, Outline { thick: false, update: false }; 10, 24, Outline { thick: true, update: true }),
        two_steps!(10, 7, Outline { thick: false, update: false }; 13, 24, Outline { thick: true, update: true }),
        two_steps!(13, 28, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 3, 24, Outline { thick: true, update: true }),
        two_steps!(12, 19, Oval { right: true }; 3, 14, Oval { right: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(8, 19, Oval { right: true }; 0, 14, Oval { right: true }),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: false, update: false }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(11, 19, Oval { right: true }; 0, 14, Oval { right: true }),
        two_steps!(11, 23, Control; 1, 0, Break),
        two_steps!(12, 15, Break; 3, 15, Outline { thick: false, update: false }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 4, 15, Outline { thick: true, update: true }),
        two_steps!(8, 24, Oval { right: true }; 12, 15, Oval { right: true }),
        two_steps!(8, 7, Oval { right: true }; 4, 15, Oval { right: true }),
        two_steps!(12, 24, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 12, Oval { right: true }; 12, 16, Oval { right: true }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 5, 6, Control),
        two_steps!(0, 0, Break; 5, 5, Break),
        two_steps!(7, 8, Outline { thick: false, update: false }; 5, 6, Control),
        two_steps!(0, 0, Break; 4, 5, Break),
        two_steps!(4, 6, Outline { thick: true, update: false }; 8, 5, Break),
        two_steps!(8, 6, Outline { thick: true, update: false }; 0, 4, Break),
        two_steps!(6, 4, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 3, 12, Break),
        two_steps!(12, 18, Oval { right: false }; 11, 28, Control),
        two_steps!(7, 30, Outline { thick: true, update: true }; 3, 3, Control),
        two_steps!(2, 0, Break; 8, 1, Break),
        two_steps!(4, 5, Outline { thick: false, update: true }; 3, 6, Control),
        two_steps!(0, 0, Break; 0, 16, Break),
        two_steps!(9, 16, Outline { thick: false, update: false }; 3, 7, Control),
        two_steps!(0, 0, Break; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 10, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 4, 6, Break),
        two_steps!(4, 6, Outline { thick: false, update: false }; 8, 6, Break),
        two_steps!(8, 6, Outline { thick: false, update: false }; 10, 6, Control),
        two_steps!(0, 0, Break; 0, 21, Break),
        two_steps!(1, 23, Control; 2, 24, Outline { thick: true, update: true }),
        two_steps!(4, 18, Control; 3, 7, Outline { thick: true, update: true }),
        two_steps!(8, 7, Outline { thick: true, update: true }; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 19, Oval { right: true }; 8, 14, Oval { right: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 16, Break; 7, 16, Outline { thick: true, update: true }),
        two_steps!(7, 7, Break; 7, 24, Outline { thick: true, update: true }),
        two_steps!(12, 20, Oval { right: true }; 7, 16, Oval { right: true }),
        two_steps!(0, 5, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 15, Break; 10, 15, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 10, 27, Control),
        two_steps!(1, 0, Break; 7, 3, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 7, 23, Control),
        two_steps!(1, 0, Break; 5, 3, Break),
        two_steps!(7, 6, Outline { thick: true, update: true }; 9, 7, Control),
        two_steps!(0, 0, Break; 3, 6, Break),
        two_steps!(6, 9, Control; 9, 6, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 23, Outline { thick: true, update: true }),
        two_steps!(6, 23, Outline { thick: false, update: true }; 6, 27, Outline { thick: false, update: false }),
        two_steps!(12, 23, Outline { thick: false, update: true }; 12, 7, Outline { thick: false, update: false }),
        two_steps!(0, 0, Break; 0, 0, Break),
    ]
};


