#![allow(missing_docs)]

use super::font::*;
use ranged_integers::*;
use GlyphConnectionType::*;


/// The main entity containing all the glyph tables.
// 2298 steps, 415 glyphs, 7724 bytes
pub static TABLES: [GlyphTable; 4] = [
    GLYPHS_LATIN,
    GLYPHS_LATIN_EXTA_UNIMPL,
    GLYPHS_GREEK,
    GLYPHS_CYRILLIC,
];

macro_rules! two_steps {
    ($x1:literal, $y1:literal, $z1:expr; $x2:literal, $y2:literal, $z2:expr) => {
        GlyphStep::to_gdata(
            GlyphStep{coord: GlyphCoord{x: r!([] $x1), y: r!([] $y1)}, tp: $z1},
            GlyphStep{coord: GlyphCoord{x: r!([] $x2), y: r!([] $y2)}, tp: $z2},
        )
    };
}

pub const GLYPHS_LATIN : GlyphTable = GlyphTable {
    basechar: ' ',
    addr: &[0, 1, 5, 9, 17, 28, 44, 52, 54, 57, 60, 66, 70, 73, 75, 77, 79, 90, 93, 100, 108, 112, 118, 127, 129, 144, 153, 157, 161, 164, 168, 171, 180, 194, 199, 208, 213, 218, 223, 227, 234, 239, 245, 249, 253, 255, 259, 262, 271, 276, 287, 293, 302, 305, 310, 312, 316, 319, 322, 325, 329, 331, 335, 338, 340, 342, 352, 357, 362, 368, 377, 382, 390, 395, 399, 405, 409, 412, 420, 425, 434, 440, 446, 450, 459, 464, 468, 471, 476, 480, 488, 492, 501, 503, 512],
    data: &[
        two_steps!(0, 0, Break; 6, 1, Break),
        two_steps!(6, 15, Outline { thick: true, update: true }; 6, 23, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 4, 1, Break),
        two_steps!(4, 7, Outline { thick: true, update: true }; 8, 1, Break),
        two_steps!(8, 7, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 24, Outline { thick: true, update: true }; 0, 6, Break),
        two_steps!(12, 6, Outline { thick: false, update: true }; 0, 18, Break),
        two_steps!(12, 18, Outline { thick: false, update: true }; 12, 2, Break),
        two_steps!(0, 0, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(0, 11, Control; 6, 12, Outline { thick: true, update: true }),
        two_steps!(12, 13, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(6, 0, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(6, 4, Break; 6, 1, Control),
        two_steps!(3, 1, Outline { thick: false, update: true }; 0, 1, Control),
        two_steps!(0, 4, Outline { thick: false, update: true }; 0, 7, Control),
        two_steps!(4, 7, Outline { thick: false, update: true }; 12, 1, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 7, 17, Outline { thick: false, update: true }),
        two_steps!(12, 17, Control; 12, 21, Outline { thick: false, update: true }),
        two_steps!(12, 24, Control; 9, 24, Outline { thick: false, update: true }),
        two_steps!(6, 24, Control; 6, 21, Outline { thick: false, update: true }),
        two_steps!(12, 24, Break; 6, 11, Outline { thick: false, update: true }),
        two_steps!(0, 1, Control; 12, 2, Outline { thick: false, update: false }),
        two_steps!(0, 18, Control; 3, 24, Outline { thick: true, update: true }),
        two_steps!(9, 26, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 6, 6, Outline { thick: true, update: true }),
        two_steps!(7, 1, Break; 0, 12, Control),
        two_steps!(7, 24, Outline { thick: true, update: true }; 5, 1, Break),
        two_steps!(12, 12, Control; 5, 24, Outline { thick: true, update: true }),
        two_steps!(6, 12, Break; 6, 5, Outline { thick: false, update: false }),
        two_steps!(1, 9, Outline { thick: false, update: false }; 11, 9, Outline { thick: false, update: false }),
        two_steps!(2, 17, Outline { thick: true, update: false }; 10, 17, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 12, Outline { thick: true, update: true }),
        two_steps!(6, 5, Break; 6, 19, Outline { thick: false, update: true }),
        two_steps!(8, 21, Break; 8, 24, Outline { thick: true, update: true }),
        two_steps!(6, 28, Outline { thick: false, update: true }; 3, 12, Break),
        two_steps!(9, 12, Outline { thick: false, update: true }; 6, 23, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 11, 2, Break),
        two_steps!(1, 23, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(0, 2, Control; 1, 12, Outline { thick: true, update: true }),
        two_steps!(0, 23, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 23, Control; 11, 12, Outline { thick: true, update: true }),
        two_steps!(12, 2, Control; 6, 1, Outline { thick: true, update: true }),
        two_steps!(11, 6, Break; 1, 18, Outline { thick: false, update: true }),
        two_steps!(2, 12, Break; 9, 1, Outline { thick: false, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 1, Control; 7, 2, Outline { thick: false, update: true }),
        two_steps!(14, 3, Control; 7, 14, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Control; 12, 5, Outline { thick: false, update: true }),
        two_steps!(12, 12, Control; 4, 12, Outline { thick: false, update: true }),
        two_steps!(12, 12, Control; 12, 19, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(9, 24, Break; 9, 1, Outline { thick: true, update: true }),
        two_steps!(0, 17, Outline { thick: false, update: true }; 12, 17, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: false, update: false }; 0, 12, Outline { thick: true, update: true }),
        two_steps!(12, 12, Control; 12, 19, Outline { thick: true, update: true }),
        two_steps!(12, 25, Control; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 2, Break; 0, 1, Control),
        two_steps!(0, 18, Outline { thick: true, update: true }; 2, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 10, 24, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 11, Control),
        two_steps!(1, 14, Outline { thick: true, update: true }; 12, 1, Outline { thick: false, update: true }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 12, Break),
        two_steps!(12, 10, Control; 12, 6, Outline { thick: false, update: true }),
        two_steps!(12, 1, Control; 6, 1, Outline { thick: false, update: true }),
        two_steps!(0, 1, Control; 0, 6, Outline { thick: false, update: true }),
        two_steps!(0, 10, Control; 6, 12, Outline { thick: false, update: true }),
        two_steps!(12, 14, Control; 12, 20, Outline { thick: true, update: true }),
        two_steps!(6, 30, Control; 0, 20, Outline { thick: true, update: true }),
        two_steps!(0, 14, Control; 6, 12, Outline { thick: true, update: true }),
        two_steps!(1, 23, Break; 13, 25, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 12, 2, Control),
        two_steps!(6, 2, Outline { thick: true, update: true }; 0, 3, Control),
        two_steps!(0, 8, Outline { thick: true, update: true }; 3, 15, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 6, 6, Break),
        two_steps!(6, 8, Outline { thick: true, update: true }; 6, 22, Break),
        two_steps!(6, 23, Outline { thick: true, update: true }; 7, 6, Break),
        two_steps!(7, 7, Outline { thick: true, update: true }; 8, 23, Break),
        two_steps!(5, 27, Outline { thick: false, update: true }; 12, 5, Break),
        two_steps!(0, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 10, Break; 12, 10, Outline { thick: false, update: true }),
        two_steps!(0, 14, Break; 12, 14, Outline { thick: false, update: true }),
        two_steps!(0, 5, Break; 12, 14, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 5, Break),
        two_steps!(0, 1, Control; 6, 1, Outline { thick: true, update: true }),
        two_steps!(14, 3, Control; 10, 8, Outline { thick: true, update: true }),
        two_steps!(6, 11, Control; 6, 15, Outline { thick: true, update: true }),
        two_steps!(6, 24, Break; 6, 26, Outline { thick: true, update: true }),
        two_steps!(8, 8, Break; 8, 18, Outline { thick: false, update: false }),
        two_steps!(3, 8, Control; 3, 12, Outline { thick: false, update: true }),
        two_steps!(3, 17, Control; 9, 18, Outline { thick: false, update: true }),
        two_steps!(13, 16, Control; 13, 10, Outline { thick: false, update: true }),
        two_steps!(13, 4, Control; 6, 4, Outline { thick: false, update: true }),
        two_steps!(0, 3, Control; 0, 13, Outline { thick: false, update: true }),
        two_steps!(1, 24, Control; 13, 24, Outline { thick: false, update: true }),
        two_steps!(0, 24, Break; 6, 1, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 2, 17, Break),
        two_steps!(10, 17, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(13, 25, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 12, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(12, 12, Control; 12, 6, Outline { thick: false, update: true }),
        two_steps!(12, 1, Control; 0, 1, Outline { thick: false, update: true }),
        two_steps!(12, 2, Break; 0, 0, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 12, Outline { thick: true, update: true }),
        two_steps!(12, 1, Control; 0, 1, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: false }; 0, 12, Outline { thick: true, update: true }),
        two_steps!(9, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: false }),
        two_steps!(0, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 2, Break),
        two_steps!(0, 1, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 12, 23, Outline { thick: true, update: true }),
        two_steps!(12, 12, Outline { thick: false, update: true }; 7, 12, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(12, 12, Outline { thick: false, update: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: false, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 10, 1, Break),
        two_steps!(10, 20, Outline { thick: true, update: true }; 8, 27, Control),
        two_steps!(3, 23, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 1, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(6, 14, Outline { thick: false, update: true }; 12, 1, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 0, 1, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 12, 1, Control),
        two_steps!(6, 1, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 1, Control; 12, 6, Outline { thick: true, update: true }),
        two_steps!(12, 14, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 0, 1, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 12, 1, Control),
        two_steps!(6, 1, Outline { thick: true, update: true }; 6, 14, Break),
        two_steps!(13, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 1, Control; 12, 6, Outline { thick: true, update: true }),
        two_steps!(12, 14, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 2, Break),
        two_steps!(0, 0, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(0, 11, Control; 6, 12, Outline { thick: true, update: true }),
        two_steps!(12, 13, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 0, 24, Control),
        two_steps!(4, 24, Outline { thick: true, update: true }; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 1, Outline { thick: true, update: true }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(1, 24, Outline { thick: true, update: true }; 6, 1, Outline { thick: true, update: true }),
        two_steps!(11, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 11, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: false }; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(3, 1, Outline { thick: true, update: true }; 3, 24, Outline { thick: true, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 1, 2, Break),
        two_steps!(11, 23, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Outline { thick: true, update: true }; 3, 7, Break),
        two_steps!(6, 2, Outline { thick: true, update: true }; 9, 7, Outline { thick: true, update: true }),
        two_steps!(0, 23, Break; 12, 23, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 8, 6, Outline { thick: true, update: true }),
        two_steps!(0, 8, Break; 1, 7, Control),
        two_steps!(6, 7, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(12, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(0, 14, Control; 0, 19, Outline { thick: true, update: true }),
        two_steps!(1, 25, Control; 14, 24, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 18, Outline { thick: false, update: true }; 12, 12, Control),
        two_steps!(0, 12, Outline { thick: false, update: true }; 12, 7, Break),
        two_steps!(0, 7, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 0, 17, Outline { thick: false, update: true }),
        two_steps!(0, 10, Control; 12, 11, Outline { thick: false, update: true }),
        two_steps!(0, 17, Break; 12, 17, Outline { thick: false, update: true }),
        two_steps!(12, 10, Control; 6, 10, Outline { thick: false, update: true }),
        two_steps!(0, 10, Control; 0, 17, Outline { thick: false, update: true }),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: false, update: true }),
        two_steps!(11, 24, Outline { thick: false, update: true }; 3, 24, Break),
        two_steps!(3, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(3, 3, Control; 10, 4, Outline { thick: true, update: true }),
        two_steps!(12, 24, Break; 0, 24, Control),
        two_steps!(0, 17, Outline { thick: true, update: true }; 0, 10, Control),
        two_steps!(12, 10, Outline { thick: true, update: true }; 12, 25, Outline { thick: true, update: true }),
        two_steps!(12, 30, Control; 1, 28, Outline { thick: true, update: true }),
        two_steps!(0, 0, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 14, 6, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 25, Outline { thick: true, update: true }; 6, 29, Control),
        two_steps!(3, 29, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 24, Outline { thick: true, update: false }),
        two_steps!(12, 8, Outline { thick: false, update: true }; 4, 1, Break),
        two_steps!(7, 1, Outline { thick: false, update: true }; 7, 24, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: false }),
        two_steps!(6, 7, Control; 6, 23, Outline { thick: false, update: true }),
        two_steps!(6, 6, Control; 9, 7, Outline { thick: false, update: true }),
        two_steps!(12, 7, Control; 12, 24, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 10, Break; 14, 2, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(0, 7, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 16, Outline { thick: true, update: true }),
        two_steps!(12, 7, Control; 6, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 31, Outline { thick: true, update: false }),
        two_steps!(11, 6, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 12, 31, Outline { thick: true, update: false }),
        two_steps!(0, 6, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 6, Control; 12, 8, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 6, Control),
        two_steps!(1, 12, Outline { thick: true, update: true }; 3, 14, Control),
        two_steps!(6, 15, Outline { thick: true, update: true }; 10, 16, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 25, Control),
        two_steps!(0, 24, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: false }),
        two_steps!(2, 25, Control; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(12, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 6, 11, Outline { thick: false, update: true }),
        two_steps!(10, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 26, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 0, 0, Break),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 31, Control; 1, 29, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 1, Control),
        two_steps!(5, 7, Outline { thick: true, update: true }; 6, 13, Control),
        two_steps!(3, 13, Outline { thick: true, update: true }; 6, 13, Control),
        two_steps!(5, 19, Outline { thick: true, update: true }; 4, 25, Control),
        two_steps!(8, 25, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 29, Outline { thick: false, update: true }; 4, 1, Break),
        two_steps!(8, 1, Control; 7, 7, Outline { thick: true, update: true }),
        two_steps!(6, 13, Control; 10, 13, Outline { thick: true, update: true }),
        two_steps!(6, 13, Control; 7, 19, Outline { thick: true, update: true }),
        two_steps!(8, 25, Control; 4, 25, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 3, 5, Control),
        two_steps!(6, 12, Outline { thick: false, update: true }; 9, 19, Control),
        two_steps!(12, 12, Outline { thick: false, update: true }; 0, 0, Break),
    ]
};

pub const GLYPHS_LATIN_EXTA_UNIMPL : GlyphTable = GlyphTable {
    basechar: 'Ā',
    addr: &[0, 7, 11, 19, 32, 37, 42, 49, 53, 61, 66, 73, 77, 85, 90, 99, 107, 111, 119, 127, 131, 141, 146, 154, 158, 166, 171, 180, 185, 195, 200, 210, 215, 219, 223, 227, 237, 242, 250, 258, 265, 275, 281, 289, 293, 302, 307, 315, 321, 329, 331, 341, 351, 358, 365, 371, 377, 382, 387, 392, 396, 401, 405, 410, 414, 419, 424, 429, 433, 437, 441, 445, 450, 455, 462, 467, 474, 485, 489, 498, 503, 516, 522, 532, 545, 554, 558, 562, 566, 572, 577, 588, 592, 604, 609, 614, 619, 631, 636, 642, 650, 657, 664, 669, 676, 682, 688, 692, 698, 700, 704, 706, 710, 712, 716, 718, 722, 726, 728, 731, 738, 741, 744, 746, 752, 756, 759, 761],
    data: &[
        two_steps!(0, 24, Break; 6, 3, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 2, 17, Break),
        two_steps!(10, 17, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: false, update: true }; 1, 6, Recall),
        two_steps!(0, 0, Control; 3, 4, Break),
        two_steps!(9, 4, Outline { thick: false, update: true }; 0, 24, Break),
        two_steps!(6, 3, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 17, Break; 10, 17, Outline { thick: false, update: true }),
        two_steps!(3, 0, Break; 6, 3, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 0, 8, Break),
        two_steps!(1, 7, Control; 6, 7, Outline { thick: true, update: true }),
        two_steps!(12, 7, Control; 12, 14, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: false }; 0, 14, Control),
        two_steps!(0, 19, Outline { thick: true, update: true }; 1, 25, Control),
        two_steps!(14, 24, Outline { thick: true, update: true }; 3, 2, Break),
        two_steps!(6, 6, Control; 9, 2, Outline { thick: false, update: true }),
        two_steps!(1, 4, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(12, 24, Break; 6, 30, Control),
        two_steps!(12, 29, Outline { thick: false, update: true }; 1, 6, Recall),
        two_steps!(0, 0, Control; 14, 24, Break),
        two_steps!(8, 29, Control; 14, 29, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 0, 4, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 8, 0, Break),
        two_steps!(4, 4, Outline { thick: false, update: true }; 3, 6, Recall),
        two_steps!(0, 0, Control; 8, 1, Break),
        two_steps!(5, 5, Outline { thick: false, update: true }; 12, 4, Break),
        two_steps!(0, 3, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 3, Break; 6, 0, Outline { thick: false, update: true }),
        two_steps!(10, 3, Outline { thick: false, update: true }; 3, 6, Recall),
        two_steps!(0, 0, Control; 2, 5, Break),
        two_steps!(6, 2, Outline { thick: true, update: true }; 10, 5, Outline { thick: true, update: true }),
        two_steps!(12, 3, Break; 0, 3, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(7, 1, Outline { thick: true, update: true }; 3, 6, Recall),
        two_steps!(0, 0, Control; 6, 5, Break),
        two_steps!(7, 5, Outline { thick: true, update: true }; 12, 3, Break),
        two_steps!(0, 3, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 0, Break; 6, 4, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 3, 6, Recall),
        two_steps!(0, 0, Control; 3, 4, Break),
        two_steps!(6, 8, Control; 10, 4, Outline { thick: false, update: true }),
        two_steps!(0, 5, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 5, Control; 0, 5, Outline { thick: true, update: true }),
        two_steps!(2, 1, Break; 6, 6, Control),
        two_steps!(10, 1, Outline { thick: false, update: true }; 11, 1, Break),
        two_steps!(11, 24, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(0, 17, Outline { thick: false, update: true }; 0, 10, Control),
        two_steps!(12, 11, Outline { thick: false, update: true }; 14, 0, Break),
        two_steps!(11, 7, Outline { thick: true, update: true }; 4, 4, Recall),
        two_steps!(0, 0, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(6, 12, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(0, 17, Outline { thick: false, update: true }; 0, 10, Control),
        two_steps!(12, 11, Outline { thick: false, update: true }; 9, 4, Break),
        two_steps!(15, 4, Outline { thick: false, update: true }; 0, 3, Break),
        two_steps!(12, 3, Outline { thick: true, update: false }; 0, 12, Outline { thick: true, update: true }),
        two_steps!(9, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: true, update: true }; 5, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 3, 6, Break),
        two_steps!(9, 6, Outline { thick: true, update: true }; 0, 3, Break),
        two_steps!(12, 3, Outline { thick: true, update: false }; 0, 3, Outline { thick: true, update: true }),
        two_steps!(0, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 0, Break; 6, 4, Control),
        two_steps!(9, 0, Outline { thick: false, update: true }; 5, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 3, 4, Break),
        two_steps!(6, 8, Control; 10, 4, Outline { thick: false, update: true }),
        two_steps!(0, 3, Break; 12, 3, Outline { thick: true, update: false }),
        two_steps!(0, 12, Outline { thick: false, update: true }; 10, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 7, 1, Outline { thick: true, update: true }),
        two_steps!(5, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(6, 5, Break; 7, 5, Outline { thick: true, update: true }),
        two_steps!(0, 3, Break; 12, 3, Outline { thick: true, update: false }),
        two_steps!(0, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 28, Control; 12, 28, Outline { thick: true, update: true }),
        two_steps!(5, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(11, 24, Break; 6, 29, Control),
        two_steps!(12, 29, Outline { thick: false, update: true }; 0, 3, Break),
        two_steps!(12, 3, Outline { thick: true, update: false }; 0, 12, Outline { thick: true, update: true }),
        two_steps!(9, 12, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 3, 0, Break),
        two_steps!(6, 4, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(5, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 6, 8, Control),
        two_steps!(10, 4, Outline { thick: false, update: true }; 12, 4, Break),
        two_steps!(0, 3, Control; 0, 14, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 12, 23, Outline { thick: true, update: true }),
        two_steps!(12, 12, Outline { thick: false, update: true }; 7, 12, Outline { thick: false, update: true }),
        two_steps!(2, 3, Break; 6, 0, Outline { thick: false, update: true }),
        two_steps!(10, 3, Outline { thick: false, update: true }; 7, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 2, 7, Break),
        two_steps!(6, 4, Outline { thick: false, update: true }; 10, 7, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 0, 4, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(12, 23, Outline { thick: true, update: true }; 12, 12, Outline { thick: false, update: true }),
        two_steps!(7, 12, Outline { thick: false, update: true }; 3, 0, Break),
        two_steps!(6, 4, Control; 9, 0, Outline { thick: false, update: true }),
        two_steps!(7, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(3, 5, Break; 6, 8, Control),
        two_steps!(9, 5, Outline { thick: false, update: true }; 7, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 6, 1, Break),
        two_steps!(7, 1, Outline { thick: true, update: true }; 7, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 6, 5, Break),
        two_steps!(7, 5, Outline { thick: true, update: true }; 7, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 7, 25, Break),
        two_steps!(6, 27, Outline { thick: false, update: true }; 12, 24, Break),
        two_steps!(0, 24, Control; 0, 17, Outline { thick: true, update: true }),
        two_steps!(0, 10, Control; 12, 10, Outline { thick: true, update: true }),
        two_steps!(12, 25, Outline { thick: true, update: true }; 12, 30, Control),
        two_steps!(1, 28, Outline { thick: true, update: true }; 7, 4, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 8, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 3, 3, Break),
        two_steps!(6, 0, Outline { thick: false, update: true }; 9, 3, Outline { thick: false, update: true }),
        two_steps!(2, 4, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 12, Break; 14, 6, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 4, Break),
        two_steps!(2, 1, Outline { thick: false, update: true }; 5, 4, Outline { thick: false, update: true }),
        two_steps!(2, 1, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 12, Break; 11, 12, Outline { thick: false, update: true }),
        two_steps!(11, 1, Break; 11, 24, Outline { thick: true, update: true }),
        two_steps!(0, 5, Break; 14, 5, Outline { thick: false, update: true }),
        two_steps!(2, 1, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 12, Break; 14, 6, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 4, Break),
        two_steps!(4, 4, Outline { thick: false, update: true }; 3, 4, Break),
        two_steps!(9, 4, Outline { thick: false, update: true }; 6, 4, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 2, 2, Break),
        two_steps!(4, 0, Outline { thick: false, update: true }; 6, 3, Outline { thick: false, update: true }),
        two_steps!(9, 1, Outline { thick: false, update: true }; 6, 6, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 3, Break),
        two_steps!(5, 1, Outline { thick: false, update: true }; 7, 4, Outline { thick: false, update: true }),
        two_steps!(9, 2, Outline { thick: false, update: true }; 3, 4, Break),
        two_steps!(9, 4, Outline { thick: false, update: true }; 6, 4, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 2, 2, Break),
        two_steps!(10, 2, Outline { thick: false, update: true }; 6, 6, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 3, Break),
        two_steps!(9, 3, Outline { thick: false, update: true }; 3, 4, Break),
        two_steps!(9, 4, Outline { thick: false, update: true }; 6, 4, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 2, 1, Break),
        two_steps!(6, 3, Outline { thick: false, update: true }; 10, 1, Outline { thick: false, update: true }),
        two_steps!(6, 6, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 6, 5, Outline { thick: false, update: true }),
        two_steps!(9, 3, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: false, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 5, 29, Control),
        two_steps!(9, 29, Outline { thick: false, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 4, 29, Control),
        two_steps!(9, 27, Outline { thick: false, update: true }; 3, 4, Break),
        two_steps!(9, 4, Outline { thick: false, update: true }; 6, 4, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 6, 2, Break),
        two_steps!(7, 2, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 2, 1, Break),
        two_steps!(8, 1, Outline { thick: false, update: true }; 5, 1, Break),
        two_steps!(5, 24, Outline { thick: true, update: true }; 2, 24, Break),
        two_steps!(8, 24, Outline { thick: false, update: true }; 10, 1, Break),
        two_steps!(10, 20, Outline { thick: true, update: true }; 8, 27, Control),
        two_steps!(3, 23, Outline { thick: true, update: true }; 3, 4, Break),
        two_steps!(3, 5, Outline { thick: true, update: true }; 3, 11, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 25, Outline { thick: true, update: true }; 6, 29, Control),
        two_steps!(3, 29, Outline { thick: true, update: true }; 10, 5, Break),
        two_steps!(10, 20, Outline { thick: true, update: true }; 8, 27, Control),
        two_steps!(3, 23, Outline { thick: true, update: true }; 7, 3, Break),
        two_steps!(10, 1, Outline { thick: false, update: true }; 14, 3, Outline { thick: false, update: true }),
        two_steps!(6, 11, Break; 6, 25, Outline { thick: true, update: true }),
        two_steps!(6, 29, Control; 3, 29, Outline { thick: true, update: true }),
        two_steps!(3, 10, Break; 6, 7, Outline { thick: false, update: true }),
        two_steps!(9, 10, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 1, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 7, 24, Break),
        two_steps!(4, 28, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 24, Outline { thick: true, update: false }),
        two_steps!(12, 8, Outline { thick: false, update: true }; 7, 24, Break),
        two_steps!(4, 28, Outline { thick: false, update: true }; 0, 8, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Break),
        two_steps!(12, 24, Outline { thick: true, update: false }; 12, 8, Outline { thick: false, update: true }),
        two_steps!(0, 8, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 3, 0, Break),
        two_steps!(0, 4, Outline { thick: false, update: true }; 4, 5, Break),
        two_steps!(7, 5, Outline { thick: false, update: true }; 7, 24, Outline { thick: false, update: true }),
        two_steps!(7, 0, Break; 5, 2, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(7, 26, Break; 5, 29, Outline { thick: false, update: true }),
        two_steps!(4, 1, Break; 7, 1, Outline { thick: false, update: true }),
        two_steps!(7, 24, Outline { thick: false, update: true }; 9, 25, Break),
        two_steps!(6, 29, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 5, 2, Break),
        two_steps!(3, 6, Outline { thick: false, update: true }; 4, 1, Break),
        two_steps!(7, 1, Outline { thick: false, update: true }; 7, 24, Outline { thick: false, update: true }),
        two_steps!(11, 1, Break; 10, 5, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(4, 11, Break; 4, 12, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 7, 1, Outline { thick: false, update: true }),
        two_steps!(7, 24, Outline { thick: false, update: true }; 10, 12, Break),
        two_steps!(10, 13, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 11, Break; 1, 13, Outline { thick: false, update: true }),
        two_steps!(4, 1, Break; 7, 1, Outline { thick: false, update: true }),
        two_steps!(7, 24, Outline { thick: false, update: true }; 10, 8, Break),
        two_steps!(5, 13, Outline { thick: false, update: true }; 14, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 8, 0, Break),
        two_steps!(6, 4, Outline { thick: false, update: true }; 14, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 8, 2, Break),
        two_steps!(5, 6, Outline { thick: false, update: true }; 14, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 8, 23, Break),
        two_steps!(5, 27, Outline { thick: false, update: true }; 14, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 7, 22, Break),
        two_steps!(5, 28, Outline { thick: false, update: true }; 14, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(6, 4, Outline { thick: false, update: true }; 9, 1, Outline { thick: false, update: true }),
        two_steps!(14, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(3, 4, Break; 6, 6, Outline { thick: false, update: true }),
        two_steps!(9, 4, Outline { thick: false, update: true }; 2, 7, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 2, 10, Break),
        two_steps!(14, 2, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 2, Break; 0, 6, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: false }; 13, 28, Control),
        two_steps!(5, 29, Outline { thick: false, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 10, Break),
        two_steps!(14, 2, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(13, 31, Control; 6, 30, Outline { thick: true, update: true }),
        two_steps!(6, 3, Break; 0, 3, Control),
        two_steps!(0, 13, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 13, Outline { thick: true, update: true }; 12, 3, Control),
        two_steps!(6, 3, Outline { thick: true, update: true }; 2, 2, Break),
        two_steps!(10, 2, Outline { thick: false, update: true }; 15, 6, Recall),
        two_steps!(0, 0, Control; 2, 2, Break),
        two_steps!(10, 2, Outline { thick: false, update: true }; 6, 3, Break),
        two_steps!(0, 3, Control; 0, 13, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 13, Outline { thick: true, update: true }),
        two_steps!(12, 3, Control; 6, 3, Outline { thick: true, update: true }),
        two_steps!(15, 6, Recall; 0, 0, Control),
        two_steps!(3, 2, Break; 6, 5, Control),
        two_steps!(9, 2, Outline { thick: true, update: true }; 6, 3, Break),
        two_steps!(0, 3, Control; 0, 13, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 13, Outline { thick: true, update: true }),
        two_steps!(12, 3, Control; 6, 3, Outline { thick: true, update: true }),
        two_steps!(7, 0, Break; 5, 2, Outline { thick: false, update: true }),
        two_steps!(11, 0, Break; 9, 2, Outline { thick: false, update: true }),
        two_steps!(15, 6, Recall; 0, 0, Control),
        two_steps!(6, 3, Break; 5, 6, Outline { thick: false, update: true }),
        two_steps!(9, 3, Break; 8, 6, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 12, 1, Outline { thick: true, update: false }),
        two_steps!(6, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(0, 24, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(0, 1, Control; 6, 1, Outline { thick: true, update: true }),
        two_steps!(6, 17, Break; 12, 17, Outline { thick: false, update: true }),
        two_steps!(12, 10, Control; 9, 10, Outline { thick: false, update: true }),
        two_steps!(6, 10, Control; 6, 17, Outline { thick: false, update: true }),
        two_steps!(3, 2, Control; 0, 17, Outline { thick: false, update: true }),
        two_steps!(3, 30, Control; 6, 17, Outline { thick: false, update: true }),
        two_steps!(6, 24, Control; 9, 24, Outline { thick: false, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 0, 3, Break),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 3, Control),
        two_steps!(12, 9, Outline { thick: true, update: true }; 12, 14, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(8, 0, Break; 5, 2, Outline { thick: false, update: true }),
        two_steps!(2, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(8, 2, Break; 6, 6, Outline { thick: false, update: true }),
        two_steps!(2, 5, Recall; 0, 0, Control),
        two_steps!(7, 23, Break; 5, 27, Outline { thick: false, update: false }),
        two_steps!(2, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(7, 24, Break; 5, 27, Outline { thick: false, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 1, Control),
        two_steps!(12, 6, Outline { thick: true, update: true }; 12, 14, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 12, 24, Outline { thick: false, update: true }),
        two_steps!(2, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(4, 2, Break; 7, 5, Control),
        two_steps!(10, 2, Outline { thick: true, update: true }; 12, 4, Break),
        two_steps!(0, 3, Control; 0, 8, Outline { thick: false, update: true }),
        two_steps!(0, 12, Control; 6, 13, Outline { thick: true, update: true }),
        two_steps!(12, 14, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(8, 0, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(3, 7, Recall; 0, 0, Control),
        two_steps!(9, 2, Break; 6, 5, Outline { thick: false, update: true }),
        two_steps!(12, 4, Break; 0, 3, Control),
        two_steps!(0, 7, Outline { thick: false, update: true }; 0, 11, Control),
        two_steps!(6, 12, Outline { thick: true, update: true }; 12, 13, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(0, 23, Outline { thick: true, update: true }; 2, 3, Break),
        two_steps!(6, 0, Outline { thick: false, update: true }; 10, 3, Outline { thick: false, update: true }),
        two_steps!(3, 7, Recall; 0, 0, Control),
        two_steps!(2, 6, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 6, Outline { thick: false, update: true }; 3, 5, Recall),
        two_steps!(0, 0, Control; 6, 23, Break),
        two_steps!(8, 28, Control; 3, 28, Outline { thick: false, update: false }),
        two_steps!(3, 7, Recall; 0, 0, Control),
        two_steps!(6, 24, Break; 8, 28, Control),
        two_steps!(3, 28, Outline { thick: false, update: false }; 12, 4, Break),
        two_steps!(0, 3, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(0, 11, Control; 6, 12, Outline { thick: true, update: true }),
        two_steps!(12, 13, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(2, 0, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 0, Outline { thick: false, update: true }; 3, 7, Recall),
        two_steps!(0, 0, Control; 3, 3, Break),
        two_steps!(7, 8, Control; 11, 3, Outline { thick: false, update: false }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 6, 23, Break),
        two_steps!(8, 28, Control; 3, 28, Outline { thick: false, update: false }),
        two_steps!(3, 1, Break; 3, 7, Outline { thick: true, update: true }),
        two_steps!(9, 7, Outline { thick: false, update: false }; 2, 25, Control),
        two_steps!(9, 24, Outline { thick: true, update: true }; 6, 23, Break),
        two_steps!(8, 28, Control; 3, 28, Outline { thick: false, update: false }),
        two_steps!(0, 4, Break; 12, 4, Outline { thick: true, update: true }),
        two_steps!(6, 4, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(2, 0, Break; 6, 3, Outline { thick: false, update: true }),
        two_steps!(10, 0, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: false }),
        two_steps!(2, 25, Control; 9, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Break; 10, 5, Outline { thick: false, update: false }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 3, 11, Break),
        two_steps!(9, 11, Outline { thick: false, update: false }; 3, 1, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: false }),
        two_steps!(2, 25, Control; 9, 24, Outline { thick: true, update: true }),
        two_steps!(3, 11, Break; 9, 11, Outline { thick: false, update: false }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 5, 1, Outline { thick: false, update: true }),
        two_steps!(7, 3, Outline { thick: false, update: true }; 9, 1, Outline { thick: false, update: true }),
        two_steps!(5, 7, Recall; 0, 0, Control),
        two_steps!(3, 7, Break; 5, 5, Outline { thick: false, update: true }),
        two_steps!(7, 7, Outline { thick: false, update: true }; 9, 5, Outline { thick: false, update: true }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(2, 2, Break; 10, 2, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(2, 2, Break; 10, 2, Outline { thick: false, update: true }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(5, 5, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 28, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(1, 24, Outline { thick: true, update: true }; 6, 1, Outline { thick: true, update: true }),
        two_steps!(11, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(7, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(6, 11, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: false }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 26, Control; 12, 24, Outline { thick: false, update: true }),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 31, Control; 1, 29, Outline { thick: true, update: true }),
        two_steps!(6, 11, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: false }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(10, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(0, 3, Break; 12, 3, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 0, Break; 7, 0, Outline { thick: false, update: true }),
        two_steps!(10, 7, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(6, 5, Break; 7, 5, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 10, 7, Recall),
        two_steps!(0, 0, Outline { thick: true, update: true }; 9, 3, Break),
        two_steps!(3, 0, Control; 4, 27, Outline { thick: false, update: true }),
    ]
};

pub const GLYPHS_GREEK : GlyphTable = GlyphTable {
    basechar: 'Ͱ',
    addr: &[0, 3, 7, 12, 18, 20, 22, 25, 29, 29, 29, 31, 36, 43, 50, 54, 58, 58, 58, 58, 58, 60, 66, 70, 72, 80, 88, 96, 96, 107, 107, 113, 126, 130, 132, 134, 137, 141, 143, 145, 147, 151, 153, 155, 158, 160, 162, 167, 169, 172, 174, 174, 178, 181, 183, 193, 195, 201, 212, 222, 230, 234, 238, 242, 246, 250, 259, 270, 274, 284, 293, 301, 308, 319, 322, 327, 333, 341, 345, 356, 365, 372, 379, 386, 395, 400, 405, 415, 419, 426, 435, 441, 447, 451, 455, 459],
    data: &[
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(12, 12, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Outline { thick: true, update: true }),
        two_steps!(11, 15, Outline { thick: true, update: true }; 0, 7, Outline { thick: false, update: false }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 12, 7, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 7, Break; 3, 3, Outline { thick: false, update: true }),
        two_steps!(9, 3, Outline { thick: true, update: true }; 9, 7, Outline { thick: false, update: true }),
        two_steps!(6, 3, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(7, 4, Break; 5, 6, Outline { thick: true, update: true }),
        two_steps!(7, 23, Break; 5, 26, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 23, Break),
        two_steps!(8, 26, Outline { thick: true, update: true }; 0, 6, Break),
        two_steps!(11, 6, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 7, Control),
        two_steps!(0, 16, Outline { thick: true, update: true }; 0, 25, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 16, Break),
        two_steps!(8, 16, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(11, 6, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 23, Outline { thick: true, update: true }),
        two_steps!(5, 15, Break; 7, 15, Outline { thick: true, update: true }),
        two_steps!(7, 6, Break; 7, 7, Outline { thick: true, update: true }),
        two_steps!(8, 23, Break; 5, 27, Outline { thick: false, update: true }),
        two_steps!(10, 1, Break; 10, 20, Outline { thick: true, update: true }),
        two_steps!(8, 27, Control; 5, 26, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 6, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 6, Outline { thick: true, update: true }),
        two_steps!(2, 9, Break; 4, 9, Outline { thick: true, update: true }),
        two_steps!(8, 9, Break; 10, 9, Outline { thick: true, update: true }),
        two_steps!(1, 4, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 1, 5, Outline { thick: true, update: true }),
        two_steps!(6, 11, Break; 6, 13, Outline { thick: true, update: true }),
        two_steps!(12, 3, Break; 2, 3, Outline { thick: true, update: true }),
        two_steps!(2, 12, Outline { thick: true, update: true }; 9, 12, Outline { thick: false, update: false }),
        two_steps!(2, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 1, 5, Outline { thick: true, update: true }),
        two_steps!(2, 3, Break; 2, 24, Outline { thick: true, update: true }),
        two_steps!(2, 12, Break; 12, 12, Outline { thick: false, update: true }),
        two_steps!(12, 3, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(2, 1, Break; 0, 5, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 9, 1, Outline { thick: false, update: true }),
        two_steps!(6, 1, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(2, 1, Break; 0, 5, Outline { thick: true, update: true }),
        two_steps!(7, 2, Break; 2, 2, Control),
        two_steps!(2, 13, Outline { thick: true, update: true }; 2, 24, Control),
        two_steps!(7, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 13, Outline { thick: true, update: true }; 12, 2, Control),
        two_steps!(7, 2, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(0, 6, Outline { thick: true, update: true }; 2, 4, Break),
        two_steps!(7, 11, Outline { thick: true, update: true }; 12, 4, Outline { thick: true, update: false }),
        two_steps!(7, 24, Outline { thick: true, update: true }; 2, 1, Break),
        two_steps!(0, 7, Outline { thick: true, update: true }; 0, 24, Break),
        two_steps!(4, 24, Outline { thick: true, update: true }; 0, 23, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 0, 4, Control),
        two_steps!(6, 4, Outline { thick: true, update: true }; 12, 4, Control),
        two_steps!(12, 14, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(8, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 0, 5, Outline { thick: true, update: true }),
        two_steps!(5, 24, Recall; 1, 0, Control),
        two_steps!(9, 27, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(1, 4, Recall; 0, 0, Outline { thick: true, update: true }),
        two_steps!(2, 4, Recall; 0, 0, Control),
        two_steps!(12, 4, Break; 0, 4, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 1, Outline { thick: true, update: true }; 5, 4, Recall),
        two_steps!(0, 0, Outline { thick: true, update: true }; 10, 5, Recall),
        two_steps!(0, 0, Outline { thick: true, update: true }; 8, 4, Recall),
        two_steps!(0, 0, Break; 15, 4, Recall),
        two_steps!(0, 0, Control; 2, 12, Break),
        two_steps!(10, 12, Outline { thick: true, update: true }; 9, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 11, 4, Recall),
        two_steps!(0, 0, Break; 0, 24, Break),
        two_steps!(6, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(13, 4, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(14, 4, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 3, 10, Break),
        two_steps!(9, 10, Outline { thick: true, update: true }; 0, 24, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 15, 4, Recall),
        two_steps!(0, 0, Control; 0, 24, Outline { thick: true, update: false }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 5, Recall; 0, 0, Control),
        two_steps!(12, 1, Outline { thick: true, update: false }; 8, 12, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 9, 5, Recall),
        two_steps!(0, 0, Outline { thick: true, update: false }; 6, 24, Break),
        two_steps!(6, 1, Outline { thick: true, update: true }; 0, 1, Control),
        two_steps!(0, 6, Outline { thick: true, update: true }; 0, 15, Control),
        two_steps!(6, 14, Outline { thick: true, update: true }; 12, 15, Control),
        two_steps!(12, 6, Outline { thick: true, update: true }; 12, 1, Control),
        two_steps!(6, 1, Outline { thick: true, update: true }; 8, 5, Recall),
        two_steps!(0, 0, Break; 0, 12, Control),
        two_steps!(6, 12, Outline { thick: true, update: true }; 12, 12, Control),
        two_steps!(12, 1, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 0, 24, Break),
        two_steps!(4, 24, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 0, 1, Control),
        two_steps!(6, 1, Outline { thick: true, update: true }; 12, 1, Control),
        two_steps!(12, 12, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(8, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(3, 3, Break; 9, 3, Outline { thick: false, update: true }),
        two_steps!(6, 3, Break; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 9, 24, Outline { thick: false, update: true }),
        two_steps!(3, 1, Break; 3, 0, Outline { thick: true, update: true }),
        two_steps!(9, 1, Break; 9, 0, Outline { thick: true, update: true }),
        two_steps!(0, 4, Break; 6, 12, Outline { thick: true, update: true }),
        two_steps!(12, 4, Outline { thick: true, update: false }; 6, 24, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 3, 0, Outline { thick: true, update: true }),
        two_steps!(9, 1, Break; 9, 0, Outline { thick: true, update: true }),
        two_steps!(1, 27, Recall; 1, 0, Control),
        two_steps!(7, 3, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(5, 27, Recall; 1, 0, Control),
        two_steps!(7, 2, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(7, 27, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(7, 2, Break; 5, 7, Outline { thick: false, update: true }),
        two_steps!(9, 27, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(7, 2, Break; 5, 5, Outline { thick: false, update: true }),
        two_steps!(5, 28, Recall; 1, 0, Control),
        two_steps!(5, 24, Recall; 1, 0, Break),
        two_steps!(12, 7, Break; 9, 26, Control),
        two_steps!(4, 24, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(1, 16, Outline { thick: true, update: true }; 1, 7, Control),
        two_steps!(4, 7, Outline { thick: true, update: true }; 10, 7, Control),
        two_steps!(13, 24, Outline { thick: true, update: true }; 0, 31, Break),
        two_steps!(0, 9, Control; 2, 4, Outline { thick: true, update: true }),
        two_steps!(8, 1, Control; 12, 5, Outline { thick: true, update: true }),
        two_steps!(12, 10, Control; 5, 10, Outline { thick: true, update: true }),
        two_steps!(12, 10, Control; 12, 16, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 1, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 6, 12, Outline { thick: true, update: true }),
        two_steps!(10, 6, Outline { thick: true, update: false }; 5, 23, Outline { thick: true, update: true }),
        two_steps!(12, 5, Break; 0, 3, Control),
        two_steps!(3, 8, Outline { thick: true, update: true }; 12, 12, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 0, 23, Control),
        two_steps!(2, 17, Outline { thick: true, update: true }; 8, 12, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 6, Control),
        two_steps!(0, 11, Outline { thick: true, update: true }; 0, 15, Control),
        two_steps!(9, 15, Outline { thick: true, update: true }; 0, 15, Control),
        two_steps!(0, 19, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(12, 23, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(6, 9, Outline { thick: true, update: true }; 0, 17, Control),
        two_steps!(0, 19, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(8, 24, Outline { thick: true, update: true }; 13, 24, Control),
        two_steps!(10, 28, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 15, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: false }),
        two_steps!(0, 7, Control; 6, 7, Outline { thick: true, update: true }),
        two_steps!(12, 7, Control; 11, 31, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 2, 1, Control),
        two_steps!(2, 12, Outline { thick: true, update: true }; 2, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 10, 24, Control),
        two_steps!(10, 12, Outline { thick: true, update: true }; 10, 1, Control),
        two_steps!(6, 1, Outline { thick: true, update: true }; 2, 12, Break),
        two_steps!(10, 12, Outline { thick: false, update: true }; 6, 10, Break),
        two_steps!(6, 25, Control; 10, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 7, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 0, 24, Break),
        two_steps!(7, 12, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: false }),
        two_steps!(6, 4, Outline { thick: true, update: true }; 2, 1, Control),
        two_steps!(2, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 16, Outline { thick: true, update: true }; 0, 31, Outline { thick: true, update: false }),
        two_steps!(2, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(11, 24, Control; 12, 8, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(5, 24, Outline { thick: true, update: true }; 14, 14, Control),
        two_steps!(11, 7, Outline { thick: true, update: true }; 12, 1, Outline { thick: false, update: true }),
        two_steps!(0, 1, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(0, 11, Control; 12, 12, Outline { thick: false, update: true }),
        two_steps!(0, 11, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 21, Control; 8, 21, Outline { thick: true, update: true }),
        two_steps!(13, 21, Control; 11, 25, Outline { thick: false, update: true }),
        two_steps!(6, 7, Break; 0, 7, Control),
        two_steps!(0, 16, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 16, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(6, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 7, Outline { thick: true, update: true }; 2, 7, Break),
        two_steps!(2, 24, Outline { thick: true, update: true }; 9, 7, Break),
        two_steps!(7, 25, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 31, Break; 0, 17, Control),
        two_steps!(3, 11, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(11, 15, Outline { thick: true, update: true }; 10, 23, Control),
        two_steps!(1, 21, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 7, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 10, 29, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 5, Control),
        two_steps!(0, 16, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 13, 11, Control),
        two_steps!(3, 10, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 7, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(6, 24, Control; 10, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Control),
        two_steps!(4, 24, Outline { thick: true, update: true }; 12, 22, Control),
        two_steps!(12, 7, Outline { thick: true, update: true }; 3, 7, Break),
        two_steps!(0, 7, Control; 0, 15, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 7, Control; 6, 7, Outline { thick: true, update: true }),
        two_steps!(6, 31, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 29, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 29, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Control; 6, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 7, Outline { thick: true, update: true }),
        two_steps!(6, 1, Break; 6, 31, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Control),
        two_steps!(2, 24, Outline { thick: true, update: true }; 6, 24, Control),
        two_steps!(6, 12, Outline { thick: true, update: true }; 6, 24, Control),
        two_steps!(9, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 7, Outline { thick: true, update: true }; 9, 27, Recall),
        two_steps!(1, 0, Control; 3, 1, Break),
        two_steps!(3, 0, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 0, Outline { thick: true, update: true }; 5, 28, Recall),
        two_steps!(1, 0, Control; 3, 1, Break),
        two_steps!(3, 0, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 0, Outline { thick: true, update: true }; 15, 27, Recall),
        two_steps!(1, 0, Control; 7, 3, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 5, 28, Recall),
        two_steps!(1, 0, Control; 7, 3, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 9, 28, Recall),
        two_steps!(1, 0, Control; 7, 3, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 11, 4, Recall),
        two_steps!(0, 0, Break; 12, 24, Break),
        two_steps!(11, 28, Control; 7, 28, Outline { thick: false, update: true }),
    ]
};

pub const GLYPHS_CYRILLIC : GlyphTable = GlyphTable {
    basechar: 'Ѐ',
    addr: &[0, 8, 18, 26, 31, 38, 47, 53, 63, 67, 78, 87, 93, 99, 104, 113, 118, 120, 126, 128, 130, 138, 140, 145, 153, 155, 160, 162, 169, 171, 173, 175, 177, 179, 181, 183, 189, 191, 193, 198, 202, 207, 214, 220, 227, 232, 237, 248, 255, 257, 266, 276, 279, 287, 289, 295, 304, 306, 311, 316, 323, 328, 334, 343, 347, 353, 358, 362, 369, 379, 383, 389, 394, 400, 408, 415, 423, 429, 435, 447, 454, 456, 458, 467, 472, 478, 487, 491, 497, 503, 514, 524, 531, 535, 539, 544],
    data: &[
        two_steps!(0, 4, Break; 12, 4, Outline { thick: true, update: false }),
        two_steps!(0, 14, Outline { thick: true, update: true }; 9, 14, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 0, Break; 7, 3, Outline { thick: true, update: true }),
        two_steps!(0, 4, Break; 12, 4, Outline { thick: true, update: false }),
        two_steps!(0, 14, Outline { thick: true, update: true }; 9, 14, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(4, 1, Break; 3, 1, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 9, 1, Outline { thick: true, update: true }),
        two_steps!(6, 1, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(3, 24, Outline { thick: true, update: true }; 3, 12, Break),
        two_steps!(13, 9, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(13, 25, Control; 7, 24, Outline { thick: true, update: true }),
        two_steps!(12, 4, Break; 0, 4, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 7, 0, Break),
        two_steps!(5, 3, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(0, 1, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 10, 12, Outline { thick: true, update: true }),
        two_steps!(12, 2, Break; 0, 0, Control),
        two_steps!(0, 7, Outline { thick: false, update: true }; 0, 11, Control),
        two_steps!(6, 12, Outline { thick: true, update: true }; 12, 13, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(0, 23, Outline { thick: true, update: true }; 3, 1, Break),
        two_steps!(9, 1, Outline { thick: false, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 3, 3, Break),
        two_steps!(9, 3, Outline { thick: false, update: true }; 6, 3, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 3, 24, Break),
        two_steps!(9, 24, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(3, 0, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 0, Outline { thick: true, update: true }; 10, 1, Break),
        two_steps!(10, 20, Outline { thick: true, update: true }; 8, 27, Control),
        two_steps!(3, 23, Outline { thick: true, update: true }; 0, 21, Break),
        two_steps!(0, 24, Control; 2, 24, Outline { thick: true, update: true }),
        two_steps!(4, 24, Control; 3, 1, Outline { thick: true, update: true }),
        two_steps!(8, 1, Outline { thick: true, update: true }; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 12, Control; 8, 11, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 12, Break),
        two_steps!(7, 12, Outline { thick: true, update: true }; 7, 1, Break),
        two_steps!(7, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 12, 12, Control),
        two_steps!(7, 12, Outline { thick: true, update: true }; 6, 1, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 12, Break; 13, 9, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 12, 1, Outline { thick: false, update: false }),
        two_steps!(12, 24, Outline { thick: false, update: false }; 7, 0, Break),
        two_steps!(5, 3, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(5, 0, Break; 7, 4, Outline { thick: true, update: true }),
        two_steps!(0, 18, Control; 9, 17, Outline { thick: true, update: true }),
        two_steps!(12, 1, Break; 12, 24, Control),
        two_steps!(3, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(5, 1, Break; 6, 3, Control),
        two_steps!(8, 1, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(6, 24, Break; 6, 28, Outline { thick: true, update: true }),
        two_steps!(1, 4, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(12, 1, Outline { thick: false, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 26, Control; 12, 17, Outline { thick: true, update: true }),
        two_steps!(12, 10, Control; 0, 12, Outline { thick: true, update: true }),
        two_steps!(2, 4, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(3, 25, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(3, 24, Break; 3, 1, Outline { thick: true, update: true }),
        two_steps!(9, 1, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(0, 29, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 29, Outline { thick: true, update: true }),
        two_steps!(5, 4, Recall; 0, 0, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 1, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 1, Control),
        two_steps!(12, 5, Outline { thick: false, update: true }; 12, 12, Control),
        two_steps!(4, 12, Outline { thick: false, update: true }; 12, 12, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(0, 23, Outline { thick: true, update: true }; 6, 23, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 6, 23, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 4, 1, Break),
        two_steps!(6, 3, Control; 8, 1, Outline { thick: true, update: true }),
        two_steps!(11, 4, Recall; 0, 0, Break),
        two_steps!(0, 21, Break; 0, 24, Control),
        two_steps!(2, 24, Outline { thick: true, update: true }; 4, 24, Control),
        two_steps!(3, 1, Outline { thick: true, update: true }; 12, 1, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 13, 4, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 8, 4, Recall),
        two_steps!(0, 0, Break; 15, 4, Recall),
        two_steps!(0, 0, Control; 0, 26, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 0, 5, Recall),
        two_steps!(0, 0, Control; 3, 4, Recall),
        two_steps!(0, 0, Control; 4, 5, Recall),
        two_steps!(0, 0, Break; 0, 18, Control),
        two_steps!(10, 17, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(12, 24, Control; 3, 24, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 26, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 8, 5, Recall),
        two_steps!(0, 0, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 9, 1, Outline { thick: true, update: false }),
        two_steps!(13, 24, Outline { thick: true, update: true }; 13, 28, Outline { thick: true, update: true }),
        two_steps!(0, 15, Control; 12, 12, Outline { thick: true, update: true }),
        two_steps!(12, 1, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 6, 24, Outline { thick: true, update: true }),
        two_steps!(6, 7, Outline { thick: false, update: false }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 1, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(5, 24, Outline { thick: true, update: true }; 5, 7, Outline { thick: true, update: false }),
        two_steps!(10, 24, Outline { thick: true, update: true }; 10, 1, Outline { thick: true, update: false }),
        two_steps!(13, 24, Outline { thick: true, update: true }; 13, 28, Outline { thick: true, update: true }),
        two_steps!(3, 1, Outline { thick: true, update: true }; 3, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 17, Outline { thick: true, update: true }),
        two_steps!(12, 11, Control; 3, 11, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: true, update: true }; 9, 24, Control),
        two_steps!(8, 18, Outline { thick: true, update: true }; 9, 11, Control),
        two_steps!(0, 11, Outline { thick: true, update: true }; 12, 1, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(11, 24, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(11, 11, Control; 0, 11, Outline { thick: true, update: true }),
        two_steps!(12, 1, Control; 12, 12, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 24, Outline { thick: true, update: false }),
        two_steps!(1, 12, Outline { thick: false, update: true }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 12, Break; 4, 12, Outline { thick: true, update: true }),
        two_steps!(4, 24, Control; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 12, Outline { thick: true, update: true }),
        two_steps!(12, 1, Control; 8, 1, Outline { thick: true, update: true }),
        two_steps!(4, 1, Control; 4, 12, Outline { thick: true, update: true }),
        two_steps!(12, 24, Break; 12, 1, Outline { thick: true, update: true }),
        two_steps!(0, 1, Control; 0, 6, Outline { thick: true, update: true }),
        two_steps!(0, 12, Control; 12, 12, Outline { thick: true, update: true }),
        two_steps!(0, 24, Outline { thick: false, update: true }; 1, 6, Recall),
        two_steps!(0, 0, Control; 12, 1, Break),
        two_steps!(1, 3, Control; 1, 7, Outline { thick: true, update: true }),
        two_steps!(0, 24, Control; 3, 24, Outline { thick: true, update: true }),
        two_steps!(12, 26, Control; 12, 18, Outline { thick: true, update: true }),
        two_steps!(12, 12, Control; 1, 14, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 19, Outline { thick: true, update: true }),
        two_steps!(12, 15, Control; 0, 15, Outline { thick: true, update: true }),
        two_steps!(12, 14, Control; 12, 11, Outline { thick: false, update: true }),
        two_steps!(12, 7, Control; 0, 7, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: false, update: false }),
        two_steps!(0, 24, Outline { thick: true, update: false }; 3, 24, Break),
        two_steps!(3, 7, Outline { thick: true, update: true }; 9, 7, Outline { thick: true, update: true }),
        two_steps!(9, 24, Outline { thick: true, update: true }; 0, 29, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(12, 29, Outline { thick: true, update: true }; 5, 6, Recall),
        two_steps!(0, 0, Outline { thick: false, update: true }; 0, 7, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 6, 7, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 6, Control; 12, 10, Outline { thick: false, update: true }),
        two_steps!(12, 15, Control; 4, 15, Outline { thick: false, update: true }),
        two_steps!(12, 15, Control; 12, 20, Outline { thick: true, update: true }),
        two_steps!(12, 25, Control; 0, 24, Outline { thick: true, update: true }),
        two_steps!(7, 23, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(7, 23, Recall; 1, 0, Outline { thick: true, update: true }),
        two_steps!(4, 6, Break; 6, 9, Control),
        two_steps!(8, 6, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Break),
        two_steps!(12, 7, Outline { thick: false, update: false }; 12, 24, Outline { thick: false, update: false }),
        two_steps!(0, 22, Break; 0, 24, Control),
        two_steps!(2, 24, Outline { thick: true, update: true }; 4, 24, Control),
        two_steps!(3, 7, Outline { thick: true, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: false }; 6, 16, Outline { thick: false, update: true }),
        two_steps!(12, 7, Outline { thick: false, update: true }; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 15, Break; 12, 15, Outline { thick: false, update: true }),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 0, 7, Control),
        two_steps!(0, 15, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(6, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: false }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 31, Outline { thick: true, update: false }; 11, 6, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(0, 23, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 7, Control; 0, 16, Outline { thick: true, update: true }),
        two_steps!(0, 25, Control; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 12, 7, Outline { thick: true, update: true }),
        two_steps!(6, 7, Break; 6, 24, Outline { thick: false, update: true }),
        two_steps!(0, 7, Break; 0, 26, Control),
        two_steps!(12, 24, Outline { thick: false, update: true }; 12, 7, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 31, Control),
        two_steps!(1, 29, Outline { thick: true, update: true }; 6, 30, Break),
        two_steps!(6, 7, Outline { thick: true, update: true }; 0, 7, Control),
        two_steps!(0, 15, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(6, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(6, 7, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 9, 24, Outline { thick: true, update: true }),
        two_steps!(9, 7, Outline { thick: true, update: false }; 13, 24, Outline { thick: true, update: true }),
        two_steps!(13, 28, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 15, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 12, 24, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 12, Outline { thick: true, update: false }),
        two_steps!(12, 24, Outline { thick: true, update: true }; 12, 7, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(5, 24, Outline { thick: true, update: true }; 5, 13, Outline { thick: true, update: false }),
        two_steps!(10, 24, Outline { thick: true, update: true }; 10, 7, Outline { thick: true, update: false }),
        two_steps!(13, 24, Outline { thick: true, update: true }; 13, 28, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 3, 7, Outline { thick: true, update: true }),
        two_steps!(3, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 14, Control),
        two_steps!(3, 14, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 9, 24, Control),
        two_steps!(8, 19, Outline { thick: true, update: true }; 9, 14, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 12, 7, Break),
        two_steps!(12, 24, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 11, 24, Control),
        two_steps!(11, 19, Outline { thick: true, update: true }; 11, 14, Control),
        two_steps!(0, 14, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 7, Control; 12, 15, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 0, 24, Outline { thick: true, update: false }),
        two_steps!(0, 15, Outline { thick: false, update: true }; 0, 7, Break),
        two_steps!(0, 24, Outline { thick: true, update: true }; 0, 15, Break),
        two_steps!(4, 15, Outline { thick: true, update: true }; 4, 24, Control),
        two_steps!(8, 24, Outline { thick: true, update: true }; 12, 24, Control),
        two_steps!(12, 15, Outline { thick: true, update: true }; 12, 7, Control),
        two_steps!(8, 7, Outline { thick: true, update: true }; 4, 7, Control),
        two_steps!(4, 15, Outline { thick: true, update: true }; 12, 24, Break),
        two_steps!(12, 7, Outline { thick: true, update: true }; 0, 7, Control),
        two_steps!(0, 12, Outline { thick: true, update: true }; 0, 16, Control),
        two_steps!(12, 16, Outline { thick: true, update: true }; 0, 24, Outline { thick: false, update: true }),
        two_steps!(5, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(5, 6, Recall; 0, 0, Outline { thick: false, update: true }),
        two_steps!(0, 4, Break; 6, 4, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 12, Break; 13, 9, Control),
        two_steps!(12, 18, Outline { thick: true, update: true }; 13, 31, Control),
        two_steps!(7, 30, Outline { thick: true, update: true }; 0, 7, Break),
        two_steps!(12, 7, Outline { thick: true, update: false }; 0, 24, Outline { thick: true, update: true }),
        two_steps!(8, 1, Break; 4, 5, Outline { thick: true, update: true }),
        two_steps!(12, 7, Break; 0, 7, Control),
        two_steps!(0, 15, Outline { thick: true, update: true }; 0, 24, Control),
        two_steps!(12, 24, Outline { thick: true, update: false }; 12, 15, Outline { thick: false, update: true }),
        two_steps!(12, 7, Break; 0, 6, Control),
        two_steps!(1, 12, Outline { thick: true, update: true }; 3, 14, Control),
        two_steps!(6, 15, Outline { thick: true, update: true }; 10, 16, Control),
        two_steps!(12, 19, Outline { thick: true, update: true }; 12, 25, Control),
        two_steps!(0, 24, Outline { thick: true, update: true }; 6, 4, Break),
        two_steps!(6, 5, Outline { thick: true, update: true }; 6, 11, Break),
        two_steps!(6, 24, Outline { thick: true, update: true }; 6, 10, Break),
        two_steps!(6, 24, Outline { thick: false, update: true }; 3, 1, Break),
        two_steps!(3, 0, Outline { thick: true, update: true }; 9, 1, Break),
        two_steps!(9, 0, Outline { thick: true, update: true }; 10, 9, Break),
        two_steps!(10, 20, Outline { thick: true, update: true }; 10, 30, Control),
        two_steps!(5, 30, Outline { thick: true, update: true }; 10, 3, Break),
        two_steps!(10, 3, Outline { thick: true, update: true }; 0, 21, Break),
        two_steps!(0, 24, Control; 2, 24, Outline { thick: true, update: true }),
        two_steps!(4, 24, Control; 3, 7, Outline { thick: true, update: true }),
        two_steps!(8, 7, Outline { thick: true, update: true }; 8, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 19, Outline { thick: true, update: true }),
        two_steps!(12, 14, Control; 8, 14, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 24, Outline { thick: true, update: true }),
        two_steps!(0, 16, Break; 7, 16, Outline { thick: true, update: true }),
        two_steps!(7, 7, Break; 7, 24, Outline { thick: true, update: true }),
        two_steps!(12, 24, Control; 12, 20, Outline { thick: true, update: true }),
        two_steps!(12, 16, Control; 7, 16, Outline { thick: true, update: true }),
        two_steps!(0, 5, Break; 6, 5, Outline { thick: true, update: true }),
        two_steps!(3, 1, Break; 3, 24, Outline { thick: true, update: true }),
        two_steps!(3, 15, Break; 12, 12, Control),
        two_steps!(12, 24, Outline { thick: true, update: true }; 10, 27, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 7, 3, Break),
        two_steps!(5, 7, Outline { thick: false, update: true }; 7, 23, Recall),
        two_steps!(1, 0, Outline { thick: true, update: true }; 5, 3, Break),
        two_steps!(7, 6, Outline { thick: true, update: true }; 3, 4, Recall),
        two_steps!(2, 0, Control; 4, 6, Break),
        two_steps!(6, 9, Control; 8, 6, Outline { thick: true, update: true }),
        two_steps!(0, 7, Break; 0, 23, Outline { thick: false, update: true }),
        two_steps!(6, 23, Outline { thick: false, update: true }; 6, 27, Outline { thick: false, update: false }),
        two_steps!(12, 23, Outline { thick: false, update: true }; 12, 7, Outline { thick: false, update: false }),
        two_steps!(0, 0, Break; 0, 0, Break),
    ]
};

